const KEY='eh-streamlined-v02';
const PLAYER_KEY='eh-player-id';
const playerId=localStorage.getItem(PLAYER_KEY)||crypto.randomUUID();localStorage.setItem(PLAYER_KEY,playerId);
const playerName=localStorage.getItem('eh-player-name')||`Игрок ${playerId.slice(0,4).toUpperCase()}`;
const catalog=window.GAME_CATALOG||{spells:[],unique:[],assets:[],conditions:[],investigators:[],monsters:[],epic:[]};
const mythosCards=window.MYTHOS_CARDS||[];
const base={modeVersion:11,round:1,phase:'actions',doom:12,omen:0,gates:[0,0,0,0],openGates:[],resolvedMythosGates:[],totals:{clue:0,mystery:0},investigators:[],monsters:[],processes:[],log:[{round:1,text:'Ктулху шевелится во сне под водами Р’льеха.'}],mythos:-1,mythosDeck:[],mythosDiscard:[],currentMythos:null,mythosCardStep:0};
const fallbackRoster=[
 {name:'Акачи Оньеле',role:'Шаманка',hp:5,san:7,skills:[3,2,2,2,4],ability:'Действие: посмотрите два верхних жетона врат и верните их в выбранном порядке.'},
 {name:'Чарли Кейн',role:'Политик',hp:4,san:8,skills:[2,4,3,2,2],ability:'Действие: другой сыщик может немедленно выполнить действие приобретения активов.'},
 {name:'Диана Стэнли',role:'Раскаявшаяся культистка',hp:7,san:5,skills:[4,2,3,3,1],ability:'Монстры-культисты наносят вам меньше урона и ужаса.'},
 {name:'Жаклин Файн',role:'Ясновидящая',hp:4,san:8,skills:[4,2,3,1,3],ability:'Действие: обменяйтесь уликами с сыщиком в любой локации.'},
 {name:'Джим Калвер',role:'Музыкант',hp:7,san:5,skills:[3,3,3,2,3],ability:'Действие: каждый сыщик в вашей локации восстанавливает 1 рассудок.'},
 {name:'Лео Андерсон',role:'Руководитель экспедиции',hp:6,san:6,skills:[2,2,3,3,3],ability:'Действие: пройдите проверку Общения, чтобы получить союзника из резерва.'},
 {name:'Лили Чен',role:'Мастер боевых искусств',hp:6,san:6,skills:[2,2,2,4,3],ability:'Действие: потеряйте любое здоровье или рассудок и восстановите столько же другого показателя.'},
 {name:'Лола Хейз',role:'Актриса',hp:5,san:7,skills:[4,4,2,2,3],ability:'Действие: переместите жетон улучшения с одного навыка на другой.'},
 {name:'Марк Харриган',role:'Солдат',hp:8,san:4,skills:[1,2,2,4,4],ability:'Вас нельзя задержать, если вы сами не решите стать задержанным.'},
 {name:'Норман Уизерс',role:'Астроном',hp:5,san:7,skills:[3,1,3,2,4],ability:'Раз в раунд можете потратить рассудок вместо улики.'},
 {name:'Сайлас Марш',role:'Моряк',hp:8,san:4,skills:[1,3,3,3,3],ability:'Действие: переместитесь на одну дополнительную локацию по морскому пути.'},
 {name:'Триш Скарборо',role:'Шпионка',hp:7,san:5,skills:[1,3,4,3,2],ability:'Если у вас нет улик, получите дополнительный кубик при проверке.'}
];
const roster=catalog.investigators?.length?catalog.investigators.map(h=>({name:h.name,role:h.role,hp:h.hp,san:h.san,skills:[h.skills.Знание,h.skills.Общение,h.skills.Внимание,h.skills.Сила,h.skills.Воля],ability:[h.ability,h.reaction].filter(Boolean).join(' '),starting:h.starting,location:h.location})):fallbackRoster;
const conditionCatalog={
 debt:{name:'Долг',kind:'Соглашение · обычное',front:'Местное действие: пройдите проверку Общения. При успехе сбросьте эту карту. Расплата: переверните карту.',backs:[
  {title:'Дорогие агенты',text:'Пройдите проверку Воли. При провале потеряйте 3 рассудка. Затем сбросьте эту карту.'},
  {title:'Наёмники',text:'Пройдите проверку Силы. При провале потеряйте 3 здоровья. Затем сбросьте эту карту.'},
  {title:'Слуга поневоле',text:'Пройдите проверку Воли. При провале возьмите состояние «Амнезия». Затем сбросьте эту карту.'},
  {title:'Коллектор',text:'Пройдите проверку Общения. При провале сбросьте 2 вещи. Затем сбросьте эту карту.'},
  {title:'Местные власти',text:'Пройдите проверку Внимания. При провале переместитесь в ближайший город и возьмите состояние «Заключение», если не сбросите 1 актив-союзник. Затем сбросьте эту карту.'},
  {title:'Заключение сделки',text:'Можете взять состояние «Тёмная сделка». Если откажетесь, повысьте безысходность на 1. Затем сбросьте эту карту.'}
 ]},
 darkPact:{name:'Тёмная сделка',kind:'Соглашение',front:'Расплата: бросьте 1 кубик. Если выпала 1, переверните карту.',backs:[
  {title:'Сделка с Тёмным человеком',text:'Вы сожраны.'},
  {title:'Один из Легиона',text:'Другой сыщик на ваш выбор сожран. Затем сбросьте эту карту.'},
  {title:'Сделка с Йог-Сототом',text:'Откройте 1 врата за каждое своё заклинание. Затем передвиньте жетон знамения на 1 деление вперёд. Затем сбросьте эту карту.'}
 ]},
 blessed:{name:'Благословение',kind:'Дар',front:'При проверках успехами считаются 4, 5 и 6. Вместо второго Благословения переверните эту карту; вместо Проклятия сбросьте её. Расплата: бросьте 1 кубик; при 1–2 сбросьте карту.',backs:[
  {title:'Возлюбленный Баст',text:'Восстановите 2 здоровья и 2 рассудка. Затем переверните эту карту.'},
  {title:'Видения Гипноса',text:'Получите 2 улики. Затем переверните эту карту.'},
  {title:'Благословение Ноденса',text:'Можете сбросить 1 монстра на свой выбор. Затем переверните эту карту.'}
 ]},
 amnesia:{name:'Амнезия',kind:'Безумие',front:'После отдыха бросьте 1 кубик; при 5–6 сбросьте карту. Расплата: пройдите указанную на физической карте проверку; при провале переверните её.'},
 hallucinations:{name:'Галлюцинации',kind:'Безумие',front:'После отдыха бросьте 1 кубик; при 5–6 сбросьте карту. Расплата: пройдите указанную проверку; при провале переверните её.'},
 paranoia:{name:'Паранойя',kind:'Безумие',front:'После отдыха бросьте 1 кубик; при 5–6 сбросьте карту. Расплата: пройдите указанную проверку; при провале переверните её.'},
 detention:{name:'Заключение',kind:'Препятствие',front:'Нельзя двигаться и совершать иные действия, кроме указанного на физической карте местного действия.'},
 backInjury:{name:'Травма спины',kind:'Травма',front:'После отдыха бросьте 1 кубик; при 5–6 сбросьте карту. Расплата: пройдите указанную проверку; при провале переверните её.'},
 legInjury:{name:'Травма ноги',kind:'Травма',front:'После отдыха бросьте 1 кубик; при 5–6 сбросьте карту. Расплата: пройдите указанную проверку; при провале переверните её.'},
 internalInjury:{name:'Внутренняя травма',kind:'Травма',front:'После отдыха бросьте 1 кубик; при 5–6 сбросьте карту. Расплата: пройдите указанную проверку; при провале переверните её.'},
 cursed:{name:'Проклятие',kind:'Напасть',front:'При проверках успехом считается только 6. Вместо второго Проклятия переверните карту; вместо Благословения сбросьте её. Расплата: бросьте 1 кубик; при 4–6 сбросьте карту.'}
};
if(catalog.conditions?.length){for(const key of Object.keys(conditionCatalog))delete conditionCatalog[key];for(const c of catalog.conditions){const key=c.id||c.name;conditionCatalog[key]={name:c.name,kind:c.kind,front:c.front,reckoning:c.reckoning,automation:c.automation}}}
let state=load();
if(!state.modeVersion){state.doom=12;state.log=state.log?.length?state.log:[{round:1,text:'Ктулху шевелится во сне под водами Р’льеха.'}]}
function monsterMaxHp(m){return m.hpPerInvestigator?state.investigators.length+m.hpBonus:m.hp}
function parseStarting(starting=''){
 const parts=String(starting).split(/[;,]+/).map(x=>x.trim()).filter(Boolean),result={items:[],conditions:[],clues:0,train:0,ship:0};
 for(const part of parts){
  const amount=Math.max(1,+(part.match(/^\s*(\d+)/)?.[1]||1));
  if(/ули(ка|ки|к)/i.test(part)){result.clues+=amount;continue}
  if(/билет.+поезд/i.test(part)){result.train+=amount;continue}
  if(/билет.+(кораб|мор)/i.test(part)){result.ship+=amount;continue}
  const quoted=part.match(/«([^»]+)»/)?.[1];
  if(/состояни/i.test(part)){if(quoted)result.conditions.push(quoted);continue}
  if(quoted){result.items.push(quoted);continue}
  result.items.push(part.replace(/^\d+\s+/, '').replace(/^случайн(ый|ая|ое)\s+/i,'Случайный '));
 }
 return result;
}
function conditionKeyByName(name){return Object.keys(conditionCatalog).find(key=>conditionCatalog[key].name===name)}
function normalizeState(){state.modeVersion=12;state.phase=state.phase||'actions';state.monsters=state.monsters||[];state.openGates=state.openGates||[];state.resolvedMythosGates=state.resolvedMythosGates||[];state.totals=state.totals||{clue:0,mystery:0};state.mythosDeck=state.mythosDeck||[];state.mythosDiscard=state.mythosDiscard||[];state.mythosCardStep=state.mythosCardStep||0;state.investigators=state.investigators||[];const validMythos=new Set(mythosCards.map(x=>x.id));if(state.mythosDeck.some(id=>!validMythos.has(id))||state.mythosDiscard.some(id=>!validMythos.has(id))||(state.currentMythos&&!validMythos.has(state.currentMythos))){state.mythosDeck=[];state.mythosDiscard=[];state.currentMythos=null;state.mythosCardStep=0}const allMonsters=[...(catalog.monsters||[]),...(catalog.epic||[])];state.monsters.forEach(x=>{const m=allMonsters.find(y=>y.name===x.name);if(m){const max=monsterMaxHp(m);x.hpMax=max;x.hp=Math.min(x.hp??max,max);x.epic=Boolean(m.epic);x.reckoning=/расплат/i.test(m.effect||'')?m.effect:(x.reckoning||'')}});state.investigators.forEach(x=>{const h=roster.find(r=>r.name===x.name);x.conditions=x.conditions||[];x.items=x.items||[];x.encounterOptions=x.encounterOptions||{gate:false,clue:false,expedition:false,special:false};x.ownerId=x.ownerId||'';x.ownerName=x.ownerName||'';if(h){x.ability=h.ability;if(!x.skills||Object.values(x.skills).every(v=>v===0)){const s=h.skills;x.skills={Знание:s[0],Общение:s[1],Внимание:s[2],Сила:s[3],Воля:s[4]}}if(!x.startingResolved){const start=parseStarting(h.starting);x.items=x.items.filter(item=>!/^\d+\s+(заклинание|актив|состояние|улика|билет)/i.test(item));for(const item of start.items)if(!x.items.includes(item))x.items.push(item);x.clues=(+x.clues||0)+start.clues;x.train=Math.min(2,(+x.train||0)+start.train);x.ship=Math.min(2,(+x.ship||0)+start.ship);for(const name of start.conditions){const key=conditionKeyByName(name);if(key&&!x.conditions.some(c=>c.type===key))x.conditions.push({type:key})}x.startingResolved=true}}})}normalizeState();
let roomCode=localStorage.getItem('eh-room-code')||'';let remoteUpdatedAt=0;let applyingRemote=false;let syncTimer;
const rules=[
 {type:'official',title:'Структура раунда',text:'Фаза действий → фаза контактов → фаза Мифа. Каждый сыщик обычно выполняет до двух разных действий.'},
 {type:'official',title:'Проверки',text:'Бросьте число кубиков, равное навыку с модификаторами. 5 и 6 — успехи. Примените улучшение, один лучший бонус к навыку и все эффекты дополнительных кубиков.'},
 {type:'official',title:'Действия',text:'Путешествие, отдых, подготовка к путешествию, приобретение активов, обмен и действия компонентов. Одно и то же действие нельзя выполнить дважды за фазу.'},
 {type:'official',title:'Обмен',text:'Отдельное действие. Сыщики в одной локации могут передать друг другу любое количество имущества по взаимному согласию.'},
 {type:'official',title:'Монстры и контакты',text:'При монстрах сначала обязательные боевые контакты со всеми по одному. Если локация очищена, проведите один доступный обычный контакт.'},
 {type:'official',title:'Миф и расплата',text:'Значки карты разыгрываются слева направо. Расплата: монстры → Древний → все процессы → имущество и состояния.'},
 {type:'official',title:'Сюжетное ядро',text:'Тайны, слухи, врата, монстры, улики, контакты, бой и текст карт остаются физическими и разыгрываются без изменений.'},
 {type:'home',title:'Отдых: 3 пункта',text:'Одним действием восстановите 3 пункта суммарно между HP и SAN. Максимумы сохраняются; при монстре отдых запрещён.'},
 {type:'home',title:'Задержка: одно действие',text:'В следующую фазу действий задержанный сыщик получает 1 действие вместо 2, после чего задержка снимается.'},
 {type:'home',title:'Билеты через общение',text:'В городе без монстра потратьте действие и пройдите проверку общения. 1 успех = 1 подходящий билет; максимум 2 суммарно. При 0 успехов — ничего. Долг не применяется.'},
 {type:'home',title:'Реактивные способности',text:'Эффект, который изменяет текущий бросок, предотвращает потерю или помогает при уже начавшейся проверке, считается реакцией и не тратит действие.'},
 {type:'home',title:'Цифровая бухгалтерия',text:'Companion хранит HP/SAN, улучшения, билеты, улики, инвентарь, состояния, безысходность, знамение, процессы и журнал. Решения и броски остаются у игроков.'},
 {type:'home',title:'Без победного счёта',text:'После победы отдельный итоговый счёт не подсчитывается.'}
];
const mythos=[
 ['Знамение','Если этот значок напечатан на карте, передвиньте жетон знамения на следующее деление по часовой стрелке. Затем повысьте безысходность на 1 за каждые врата на поле с новым знаком. Кнопка «Следующее знамение» делает оба изменения автоматически.'],
 ['Расплата','Если значок есть, сначала разыграйте эффекты расплаты каждого монстра на поле, затем эффект Ктулху, затем каждую активную карту процесса, после этого имущество и состояния сыщиков. Ктулху: каждый сыщик в морской локации без жетона Древних кладёт такой жетон в свою локацию.'],
 ['Врата','Если значок есть, возьмите верхний жетон из стопки врат и положите его лицом вверх в указанную на жетоне локацию. Затем добавьте в приложение одни врата соответствующего знамения и положите в эту локацию одного случайного монстра. Если врата там уже есть, вместо вторых врат разыграйте наплыв монстров.'],
 ['Наплыв монстров','Если значок есть: найдите все врата, совпадающие с текущим знамением. Выложите из пула столько монстров, сколько указано на памятке по числу сыщиков, распределяя их как можно равномернее между этими вратами. Если совпадающих врат нет, откройте одни новые врата и положите туда одного монстра.'],
 ['Появление улик','Если значок есть, возьмите верхний жетон улики и положите его лицом вверх в указанную на обороте локацию. Увеличьте счётчик «Улики на поле» на 1. Если жетон указывает локацию с сыщиком, улика всё равно остаётся на поле до поискового контакта.'],
 ['Текст карты','Продолжайте слева направо. Немедленно выполните все оставшиеся значки, а затем полностью прочитайте и разыграйте текст карты. Если это слух, оставьте карту в игре, добавьте её в «Активные процессы» и внесите её жетоны или таймер в примечание.']
];
function load(){try{return {...structuredClone(base),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(base)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderRoomStatus();if(roomCode&&!applyingRemote&&location.protocol!=='file:'){clearTimeout(syncTimer);syncTimer=setTimeout(pushRoom,350)}}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){
 document.querySelector('#round').textContent=state.round;document.querySelector('#doom').textContent=state.doom;
 document.querySelectorAll('[data-omen]').forEach((b,i)=>b.classList.toggle('active',i===state.omen));
 document.querySelector('#gates').innerHTML=['●','☄','◐','✦'].map((x,i)=>`<label>${x}<input type="number" min="0" value="${state.gates[i]}" data-gate="${i}"></label>`).join('');
 document.querySelector('#gate-total').textContent=state.gates.reduce((a,b)=>a+(+b||0),0);document.querySelector('#monster-total').textContent=state.monsters.length;
 ['clue','mystery'].forEach(k=>document.querySelector('#'+k+'-total').value=state.totals[k]||0);
 document.querySelector('#investigator-list').innerHTML=state.investigators.length?state.investigators.map(invCard).join(''):'<article><h3>Партия ещё не началась</h3><p class="subtle">Добавьте первого сыщика. Все изменения сохраняются автоматически в этом браузере.</p></article>';
 document.querySelector('#process-list').innerHTML=state.processes.length?state.processes.map((p,i)=>`<div class="process"><div><b>${esc(p.name)}</b><div class="subtle">${esc(p.note||'Без примечания')}</div></div><div class="process-actions"><button data-edit-process="${i}" aria-label="Изменить">Изменить</button><button data-remove-process="${i}" aria-label="Завершить">Завершить</button></div></div>`).join(''):'<p class="subtle">Активных процессов нет. Слухи из карт Мифа появятся здесь автоматически.</p>';
 document.querySelector('#monster-list').innerHTML=state.monsters.length?state.monsters.map(monsterCard).join(''):'<p class="empty-monsters">На поле нет монстров. Когда появится монстр, добавьте его сюда — приложение включит его в расплату.</p>';
 document.querySelector('#story-log').innerHTML=state.log.length?state.log.slice().reverse().map(x=>`<li><b>Раунд ${x.round}</b> — ${esc(x.text)}</li>`).join(''):'<li>История ещё не началась.</li>';
 renderMythos();save();
}
function canEdit(x){return !roomCode||x.ownerId===playerId}
function logEvent(text){state.log.push({round:state.round,text})}
function invCard(x,i){const maxActions=x.delayed?1:2,editable=canEdit(x),locked=editable?'':'disabled';return `<article class="investigator ${editable?'mine':'view-only'}" data-i="${i}"><div class="inv-head"><div><h3>${esc(x.name)}</h3><span class="owner-label">${x.ownerId?(x.ownerId===playerId?'Ваш сыщик':`Играет ${esc(x.ownerName||'другой игрок')}`):'Свободен'}</span></div>${editable?`<button data-remove-inv="${i}">×</button>`:''}</div><p class="subtle">${esc(x.role||'Сыщик')} · ${x.delayed?'задержан: одно действие в эту фазу':'готов к действиям'}</p>${!x.ownerId&&roomCode?`<button class="claim-button primary" onclick="claimInvestigator(${i})">Выбрать этого сыщика</button>`:''}<div class="status-row">${vital('hp','HP',x.hp,x.hpMax,locked)}${vital('san','SAN',x.san,x.sanMax,locked)}</div><div class="action-strip">${[0,1].map(n=>`<button class="action-dot ${n<x.actions?'used':''}" data-action-dot="${n+1}" ${n>=maxActions||!editable?'disabled':''}></button>`).join('')}<b>${x.actions}/${maxActions}</b><span>действий</span></div>${investigatorAbilities(x)}<div class="inv-controls"><button data-inv-act="inventory">Инвентарь (${x.items.length})</button><button class="condition-button" data-inv-act="conditions">Состояния (${(x.conditions||[]).length})</button></div>${!editable&&roomCode?'<p class="read-only-note">Просмотр карточки · изменения доступны владельцу</p>':''}</article>`}
function catalogEntry(name){return [...catalog.spells,...catalog.assets,...catalog.unique].find(z=>z.name===name)}
function investigatorAbilities(x){const effects=x.items.map(name=>{const s=catalogEntry(name);return s?`<li><b>${esc(s.name)}</b> · ${esc(s.timing||s.type||'Имущество')}${s.check?` · проверка ${esc(s.check)}`:''}<br><span>${esc(s.text||s.effect||s.automation||'Эффект учтён в каталоге')}</span></li>`:`<li><b>${esc(name)}</b> — эффект указан на физической карте</li>`}).join(''),editable=canEdit(x);return `<section class="abilities"><h4>Навыки</h4><div class="skill-grid">${Object.entries(x.skills).map(([k,v])=>`<span><b>${esc(k)}</b><div class="skill-counter">${editable?`<button data-skill="${esc(k)}" data-delta="-1" aria-label="Понизить ${esc(k)}">−</button>`:''}<strong>${v}</strong>${editable?`<button data-skill="${esc(k)}" data-delta="1" aria-label="Повысить ${esc(k)}">+</button>`:''}</div></span>`).join('')}</div><p class="skill-hint">Изменяйте значение, когда сыщик получает улучшение или ухудшение навыка.</p><h4>Способности, вещи и заклинания</h4>${x.ability?`<p class="hero-ability"><b>Способность:</b> ${esc(x.ability)}</p>`:''}${x.location?`<p><b>Старт:</b> ${esc(x.location)}</p>`:''}${effects?`<ul>${effects}</ul>`:'<p class="subtle">Добавьте вещи и заклинания — их эффекты появятся здесь.</p>'}</section>`}
function vital(k,label,v,max,locked=''){return `<div class="vital"><label>${label}<span>${v}/${max}</span></label><div class="counter"><button data-vital="${k}" data-delta="-1" ${locked}>−</button><strong>${v}</strong><button data-vital="${k}" data-delta="1" ${locked}>+</button></div></div>`}
function renderRules(mode='all'){document.querySelector('#rules-grid').innerHTML=rules.filter(r=>mode==='all'||r.type===mode).map(r=>`<article class="rule" data-type="${r.type}"><span class="rule-tag">${r.type==='home'?'Streamlined · хоумрул':'Официальное ядро'}</span><h3>${r.title}</h3><p>${r.text}</p></article>`).join('')}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function prepareMythosDeck(){const pools={green:shuffle(mythosCards.filter(x=>x.color==='green').map(x=>x.id)),yellow:shuffle(mythosCards.filter(x=>x.color==='yellow').map(x=>x.id)),blue:shuffle(mythosCards.filter(x=>x.color==='blue').map(x=>x.id))},take=(color,n)=>pools[color].splice(0,n);const stage1=shuffle([...take('yellow',2),...take('blue',2)]),stage2=shuffle([...take('green',1),...take('yellow',3)]),stage3=shuffle([...take('green',3),...take('yellow',4)]);state.mythosDeck=[...stage1,...stage2,...stage3];state.mythosDiscard=[]}
function mythosIconStep(icon){const map={omen:['Знамение','Передвиньте знамение. Приложение автоматически уменьшит безысходность за врата нового знака.'],reckoning:['Расплата','Монстры → Ктулху → процессы → имущество и состояния. Ниже показаны все активные эффекты, известные приложению.'],gate:['Открыть врата','Вытяните физический жетон. Приложение спросит его локацию и знак и само внесёт врата в партию.'],surge:['Наплыв монстров','Распределите указанное число монстров между вратами текущего знамения.'],clue:['Появление улики','Возьмите жетон улики и положите его в указанную на жетоне локацию.'],rumor:['Слух','Карта остаётся в игре. Приложение добавит её в активные процессы после завершения карты.']};return map[icon]||[icon,'Выполните этот символ карты.']}
function drawMythosCard(){if(state.currentMythos)return;if(!state.mythosDeck.length&&!state.mythosDiscard.length)prepareMythosDeck();const id=state.mythosDeck.shift();state.currentMythos=id;state.mythosCardStep=0;state.phase='mythos';render()}
function renderMythos(){const d=document.querySelector('#mythos-step'),card=mythosCards.find(x=>x.id===state.currentMythos);if(!card){d.innerHTML=`<span>Колода Ктулху · ${state.mythosDeck.length||15} карт</span><h3>Фаза Мифа</h3><p>Нажмите «Вытянуть карту». Приложение выберет верхнюю карту подготовленной колоды и проведёт по её истории и символам.</p>`;return}const steps=[{title:card.title,text:card.story,type:'story'},...card.icons.map(icon=>{const [title,text]=mythosIconStep(icon);return{title,text,type:icon}}),{title:/слух|процесс/i.test(card.category)?'Ввести карту в игру':'Событие',text:card.effect,type:'effect'}],step=steps[state.mythosCardStep]||steps[0];let extra='';if(step.type==='gate'){const key=`${card.id}:${state.mythosCardStep}`;extra+=state.resolvedMythosGates.includes(key)?'<p class="note"><b>Врата внесены.</b> Можно переходить к следующему шагу.</p>':'<p class="note"><b>Следующий шаг:</b> нажмите «Дальше», затем укажите вытянутые врата.</p>'}if(step.type==='effect')extra+=`<p class="note"><b>Автоматизация:</b> ${esc(card.automation||'Примените описанный эффект.')}</p>${card.reckoning?`<p><b>Постоянный эффект / расплата:</b> ${esc(card.reckoning)}</p>`:''}${card.tokens?`<p><b>Жетоны:</b> ${esc(card.tokens)}</p>`:''}${card.completion?`<p><b>Завершение:</b> ${esc(card.completion)}</p>`:''}`;if(step.type==='reckoning'){const active=state.monsters.filter(x=>x.reckoning),conditions=state.investigators.flatMap(x=>(x.conditions||[]).map(c=>({investigator:x.name,data:conditionCatalog[c.type]}))).filter(x=>x.data?.reckoning||/расплат/i.test(x.data?.front||''));extra+=active.map(x=>`<p><b>${esc(x.name)}:</b> ${esc(x.reckoning)}</p>`).join('');extra+=conditions.map(x=>`<p><b>${esc(x.investigator)} · ${esc(x.data.name)}:</b> ${esc(x.data.reckoning||x.data.front)}</p>`).join('');extra+=state.processes.filter(x=>x.note).map(x=>`<p><b>${esc(x.name)}:</b> ${esc(x.note)}</p>`).join('')}d.innerHTML=`<span>${esc(card.color.toUpperCase())} · в колоде осталось ${state.mythosDeck.length} · шаг ${state.mythosCardStep+1}/${steps.length}</span><h3>${esc(step.title)}</h3><p>${esc(step.text)}</p>${extra}`}
function newInv(hero){const s=hero.skills||[0,0,0,0,0],starting=parseStarting(hero.starting),conditions=starting.conditions.map(conditionKeyByName).filter(Boolean).map(type=>({type}));return{name:hero.name,role:hero.role,ability:hero.ability||'',location:hero.location||'',hp:hero.hp,hpMax:hero.hp,san:hero.san,sanMax:hero.san,actions:0,delayed:false,train:starting.train,ship:starting.ship,clues:starting.clues,encounterOptions:{gate:false,clue:false,expedition:false,special:false},ownerId:roomCode?playerId:'',ownerName:roomCode?playerName:'',skills:{Знание:s[0],Общение:s[1],Внимание:s[2],Сила:s[3],Воля:s[4]},items:starting.items,conditions,startingResolved:true}}
function investigatorPicker(){const used=new Set(state.investigators.map(x=>x.name)),mine=state.investigators.find(x=>x.ownerId===playerId);return `<h2>${mine?'Ваш сыщик уже выбран':'Выберите своего сыщика'}</h2><p class="subtle">В комнате один телефон управляет одним сыщиком. Карточки остальных доступны для просмотра.</p><div class="roster">${roster.map((x,i)=>`<button type="button" ${used.has(x.name)||!!mine?'disabled':''} onclick="chooseInvestigator(${i})"><b>${x.name}</b><span>${x.role}</span><small>HP ${x.hp} · SAN ${x.san}</small></button>`).join('')}</div>`}
function modal(html){document.querySelector('#modal-content').innerHTML=html;document.querySelector('#modal').showModal()}
function processModal(i=-1){const p=i>=0?state.processes[i]:null;modal(`<h2>${p?'Изменить процесс':'Новый процесс или слух'}</h2><div class="form-stack"><input id="p-name" value="${esc(p?.name||'')}" placeholder="Название слуха или процесса"><textarea id="p-note" placeholder="Расплата, таймер, напоминание">${esc(p?.note||'')}</textarea><button class="primary" type="button" onclick="saveProcess(${i})">Сохранить</button></div>`)}
function editProcessModal(i){processModal(i)}
function getInv(el){const card=el.closest('[data-i]');return card?[state.investigators[+card.dataset.i],+card.dataset.i]:[]}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.tab){document.querySelectorAll('.tabs button,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.tab).classList.add('active')}
 if(b.dataset.ruleMode){document.querySelectorAll('[data-rule-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderRules(b.dataset.ruleMode)}
 if(b.dataset.omen!==undefined){state.omen=+b.dataset.omen;render()}
 if(b.dataset.removeInv!==undefined){state.investigators.splice(+b.dataset.removeInv,1);render()}
 if(b.dataset.removeProcess!==undefined){const p=state.processes.splice(+b.dataset.removeProcess,1)[0];if(p)logEvent(`Завершён активный процесс «${p.name}».`);render()}
 if(b.dataset.editProcess!==undefined){editProcessModal(+b.dataset.editProcess);return}
 if(b.dataset.removeMonster!==undefined){const m=state.monsters.splice(+b.dataset.removeMonster,1)[0];if(m)logEvent(`Монстр ${m.name} убран из локации ${m.location}.`);render()}
 if(b.dataset.monsterHp!==undefined){const x=state.monsters[+b.dataset.monsterHp],before=x.hp;x.hp=Math.max(0,Math.min(x.hpMax,x.hp+ +b.dataset.delta));if(x.hp!==before)logEvent(`${x.name}: здоровье ${before} → ${x.hp}${x.hp===0?' — монстр побеждён.':'.'}`);render()}
 if(b.dataset.actionDot){const[x]=getInv(b);x.actions=x.actions===+b.dataset.actionDot?+b.dataset.actionDot-1:+b.dataset.actionDot;render()}
 if(b.dataset.vital){const[x]=getInv(b),k=b.dataset.vital,before=x[k];x[k]=Math.max(0,Math.min(x[k+'Max'],x[k]+ +b.dataset.delta));if(x[k]!==before)logEvent(`${x.name}: ${k.toUpperCase()} ${before} → ${x[k]}.`);render()}
 if(b.dataset.skill){const[x]=getInv(b),skill=b.dataset.skill;if(!x||!canEdit(x))return;const before=x.skills[skill];x.skills[skill]=Math.max(1,Math.min(6,before+ +b.dataset.delta));if(x.skills[skill]!==before)logEvent(`${x.name}: навык «${skill}» ${before} → ${x.skills[skill]}.`);render()}
 if(b.dataset.counter==='doom'){state.doom=Math.max(0,Math.min(15,state.doom+ +b.dataset.delta));render()}
 if(b.dataset.invAct){const[x,i]=getInv(b);invAction(b.dataset.invAct,x,i)}
 if(b.dataset.act==='room'){openRoomModal();return}
 if(b.dataset.act==='add-monster'){monsterPicker();return}
 if(b.dataset.act)action(b.dataset.act);
});
document.addEventListener('change',e=>{if(e.target.dataset.gate!==undefined){const i=+e.target.dataset.gate,before=state.gates[i];state.gates[i]=Math.max(0,+e.target.value);if(before!==state.gates[i])logEvent(`Количество врат ${['●','☄','◐','✦'][i]}: ${before} → ${state.gates[i]}.`);render()}if(e.target.id?.endsWith('-total')){const k=e.target.id.replace('-total',''),before=state.totals[k]||0;state.totals[k]=Math.max(0,+e.target.value);if(before!==state.totals[k])logEvent(`${k==='clue'?'Улики на поле':'Разгаданные тайны'}: ${before} → ${state.totals[k]}.`);render()}if(e.target.dataset.field){const[x]=getInv(e.target);if(canEdit(x)){const before=x[e.target.dataset.field];x[e.target.dataset.field]=e.target.value;if(before!==x[e.target.dataset.field])logEvent(`${x.name}: изменено поле «${e.target.dataset.field}».`);render()}}});
function action(a){if(a==='round'){state.round++;state.phase='actions';state.investigators.forEach(x=>x.actions=0);logEvent('Начался новый раунд: фаза действий.');render()}if(a==='contact-phase'){state.phase='contacts';logEvent('Началась фаза контактов.');contactPhaseModal()}if(a==='add-investigator')modal(investigatorPicker());if(a==='next-omen'){advanceOmen()}if(a==='add-process')processModal();if(a==='add-log')modal('<h2>Событие истории</h2><div class="form-stack"><textarea id="log-text" placeholder="Что произошло в мире?"></textarea><button class="primary" type="button" onclick="addLog()">Добавить</button></div>');if(a==='start-mythos')drawMythosCard();if(a==='mythos-next')advanceMythosCard();if(a==='mythos-prev'){state.mythosCardStep=Math.max(0,state.mythosCardStep-1);render()}if(a==='export'){const u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const x=document.createElement('a');x.href=u;x.download='eldritch-horror-party.json';x.click();URL.revokeObjectURL(u)}if(a==='new-game'&&confirm('Очистить текущую партию?')){state=structuredClone(base);prepareMythosDeck();render()}}
function advanceOmen(){state.omen=(state.omen+1)%4;const loss=state.gates[state.omen]||0;state.doom=Math.max(0,state.doom-loss);state.log.push({round:state.round,text:`Знамение сдвинуто; безысходность повышена на ${loss}.`});render()}
function gateModal(card,step){const key=`${card.id}:${step}`,options=[...catalog.monsters].sort((a,b)=>a.name.localeCompare(b.name)).map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('');modal(`<h2>Врата и монстр</h2><p>Вытяните физический жетон врат и один жетон монстра. Приложение внесёт их одновременно.</p><div class="form-stack"><label>Локация врат<input id="mythos-gate-location" autocomplete="off" placeholder="Например, Рим"></label><label>Знак врат<select id="mythos-gate-sign"><option value="0">● — круг</option><option value="1">☄ — комета</option><option value="2">◐ — полумесяц</option><option value="3">✦ — созвездие</option></select></label><label>Вытянутый монстр<select id="mythos-gate-monster"><option value="">Выберите монстра…</option>${options}</select></label><button class="primary" type="button" onclick="saveMythosGate('${key}')">Внести врата и монстра</button></div>`)}
window.saveMythosGate=key=>{const location=document.querySelector('#mythos-gate-location').value.trim(),sign=+document.querySelector('#mythos-gate-sign').value,monsterId=document.querySelector('#mythos-gate-monster').value,m=catalog.monsters.find(x=>x.id===monsterId);if(!location)return alert('Укажите локацию, написанную на жетоне врат.');if(!m)return alert('Выберите вытянутого монстра.');state.gates[sign]=(state.gates[sign]||0)+1;state.openGates.push({location,sign,openedRound:state.round,source:'Миф'});const monsterLocation=addMonsterToState(m,location);state.resolvedMythosGates.push(key);state.log.push({round:state.round,text:`Открылись врата: ${location} (${['●','☄','◐','✦'][sign]}). Появился ${m.name}${monsterLocation===location?'':` в локации ${monsterLocation}`}.`});document.querySelector('#modal').close();state.mythosCardStep++;render()};
function advanceMythosCard(){const card=mythosCards.find(x=>x.id===state.currentMythos);if(!card)return drawMythosCard();const steps=card.icons.length+2,currentType=state.mythosCardStep>0&&state.mythosCardStep<=card.icons.length?card.icons[state.mythosCardStep-1]:'';if(currentType==='gate'){const key=`${card.id}:${state.mythosCardStep}`;if(!state.resolvedMythosGates.includes(key)){gateModal(card,state.mythosCardStep);return}}if(currentType==='omen')advanceOmen();if(state.mythosCardStep<steps-1){state.mythosCardStep++;render();return}if(/слух|процесс/i.test(card.category)&&!state.processes.some(x=>x.id===card.id))state.processes.push({id:card.id,name:card.title,note:[card.reckoning,card.tokens,card.completion].filter(Boolean).join(' · ')});state.mythosDiscard.push(state.currentMythos);state.currentMythos=null;state.mythosCardStep=0;state.phase='actions';state.round++;state.investigators.forEach(x=>x.actions=0);render()}
function invAction(a,x,i){if(a==='delay'){x.delayed=!x.delayed;x.actions=0;render()}if(a==='rest')modal(`<h2>Отдых · 3 пункта</h2><p>Распределите восстановление между HP и SAN. При монстре это действие запрещено.</p><div class="form-stack"><label>HP <input id="rest-hp" type="number" min="0" max="3" value="0"></label><label>SAN <input id="rest-san" type="number" min="0" max="3" value="0"></label><button class="primary" type="button" onclick="applyRest(${i})">Применить</button></div>`);if(a==='ticket')modal(`<h2>Подготовка к путешествию</h2><p>Только в городе без монстра. Бросьте кубики общения: 1 успех = 1 подходящий билет, максимум 2 суммарно.</p><div class="form-stack"><label>Успехов<input id="ticket-success" type="number" min="0" value="0"></label><label>Тип<select id="ticket-type"><option value="train">Поезд</option><option value="ship">Корабль</option></select></label><button class="primary" type="button" onclick="applyTicket(${i})">Получить</button></div>`);if(a==='check')modal(`<h2>Помощник проверки</h2><div class="form-stack"><label>Навык<select id="check-skill">${Object.keys(x.skills).map(k=>`<option>${k}</option>`)}</select></label><label>Базовое значение<input id="check-base" type="number" min="1" value="3"></label><label>Модификатор проверки<input id="check-mod" type="number" value="0"></label><label>Лучший бонус имущества<input id="check-bonus" type="number" min="0" value="0"></label><label>Дополнительные кубики<input id="check-extra" type="number" min="0" value="0"></label><button class="primary" type="button" onclick="calcCheck(${i})">Рассчитать</button><output id="check-result"></output></div>`);if(a==='inventory')inventoryModal(i);if(a==='conditions')conditionModal(i);if(a==='encounter')encounterSetupModal(i)}

function inventoryModal(i){const x=state.investigators[i],editable=canEdit(x);modal(`<h2>Инвентарь: ${esc(x.name)}</h2><div class="form-stack"><div>${x.items.map((z,n)=>inventoryEntry(z,i,n,editable)).join('')||'<p class="subtle">Пусто</p>'}</div>${editable?`<button class="primary" type="button" onclick="catalogPicker(${i},'spells')">+ Заклинание</button><button type="button" onclick="catalogPicker(${i},'assets')">+ Обычная вещь</button><button type="button" onclick="catalogPicker(${i},'unique')">+ Уникальная вещь</button><details><summary>Добавить другое вручную</summary><input id="item-name" placeholder="Название"><button type="button" onclick="addItem(${i})">Добавить</button></details>`:'<p class="read-only-note">Инвентарём управляет владелец сыщика.</p>'}</div>`)}
function inventoryEntry(name,i,n,editable){const item=catalogEntry(name);return `<div class="process inventory-entry"><span><b>${esc(name)}</b>${item?`<small>${esc(item.type||'Карта')} · ${esc(item.timing||'Постоянный эффект')}${item.check?` · проверка ${esc(item.check)}`:''}</small><details><summary>Чем это поможет</summary><p>${esc(item.text||item.effect||item.automation||'Эффект учтён')}</p></details>`:'<small>Эффект указан на физической карте</small>'}</span>${editable?`<button type="button" onclick="removeItem(${i},${n})">×</button>`:''}</div>`}
window.catalogPicker=(i,type)=>{const list=catalog[type]||[],title=type==='spells'?'Заклинания':type==='unique'?'Уникальные вещи':'Обычные вещи';modal(`<h2>${title}</h2><p class="subtle">Карты отсортированы по подтипу; эффект сразу появится на листе сыщика.</p><div class="catalog-grid">${[...list].sort((a,b)=>(a.type||'').localeCompare(b.type||'')||a.name.localeCompare(b.name)).map(item=>{const n=list.indexOf(item);return `<button type="button" onclick="addCatalogItem(${i},'${type}',${n})"><b>${esc(item.name)}</b><span>${esc(item.type||item.timing||'')}</span></button>`}).join('')}</div><button type="button" onclick="inventoryModal(${i})">← Назад в инвентарь</button>`)};
window.addCatalogItem=(i,type,n)=>{const x=state.investigators[i];if(!canEdit(x))return;const entry=catalog[type]?.[n]?.name;if(entry&&!x.items.includes(entry)){x.items.push(entry);logEvent(`${x.name} получает «${entry}».`)}render();inventoryModal(i)};
function encounterSetupModal(i){const x=state.investigators[i],o=x.encounterOptions||{};modal(`<h2>Контакты в локации</h2><p>Отметьте жетоны и особые возможности, которые сейчас находятся вместе с ${esc(x.name)}.</p><div class="form-stack encounter-switches"><label><input type="checkbox" id="enc-gate" ${o.gate?'checked':''}> Врата</label><label><input type="checkbox" id="enc-clue" ${o.clue?'checked':''}> Улика</label><label><input type="checkbox" id="enc-expedition" ${o.expedition?'checked':''}> Активная экспедиция</label><label><input type="checkbox" id="enc-special" ${o.special?'checked':''}> Особый контакт тайны или слуха</label><button class="primary" type="button" onclick="saveEncounterOptions(${i})">Сохранить</button></div>`)}
window.saveEncounterOptions=i=>{const x=state.investigators[i];x.encounterOptions={gate:document.querySelector('#enc-gate').checked,clue:document.querySelector('#enc-clue').checked,expedition:document.querySelector('#enc-expedition').checked,special:document.querySelector('#enc-special').checked};document.querySelector('#modal').close();render()};
function contactChoices(x){const choices=['Контакт текущей локации','Если здесь врата — контакт в Ином мире','Если здесь улика — поисковый контакт','Если здесь активная экспедиция — экспедиционный контакт','Если здесь жетон тайны или слуха — особый контакт'];return `<article class="contact-summary"><h3>${esc(x.name)}</h3><div class="combat-warning"><b>Проверьте физическое поле:</b> если здесь есть монстры, сначала проведите бой со всеми. Если после боя монстры остались, другой контакт запрещён.</div><p><b>Если локация очищена, выберите один вариант:</b></p><ul>${choices.map(c=>`<li>${c}</li>`).join('')}</ul></article>`}
function contactPhaseModal(){modal(`<h2>Фаза контактов</h2><p>Контакты разыгрываются физическими картами. Каждый сыщик проводит один доступный контакт после обязательных боёв.</p><div class="contact-list">${state.investigators.map(contactChoices).join('')||'<p>Сначала добавьте сыщиков.</p>'}</div><button class="primary wide" type="button" onclick="finishContacts()">Все закончили контакты → Фаза Мифа</button>`)}
window.finishContacts=()=>{document.querySelector('#modal').close();drawMythosCard()};

function conditionModal(i){const x=state.investigators[i],editable=canEdit(x);x.conditions=x.conditions||[];modal(`<h2>Состояния: ${esc(x.name)}</h2><p class="subtle">Приложение хранит лицевой эффект и напоминает расплату; оборот остаётся физическим.</p><div class="condition-list">${x.conditions.map((c,n)=>conditionCard(c,i,n,editable)).join('')||'<p class="subtle">Состояний пока нет.</p>'}</div>${editable?`<h3>Получить состояние</h3><div class="condition-picker">${Object.entries(conditionCatalog).sort((a,b)=>a[1].kind.localeCompare(b[1].kind)||a[1].name.localeCompare(b[1].name)).map(([key,c])=>`<button type="button" onclick="addCondition(${i},'${key}')"><b>${c.name}</b><span>${c.kind}</span></button>`).join('')}</div>`:'<p class="read-only-note">Состояниями управляет владелец сыщика.</p>'}`)}
function conditionCard(c,i,n,editable){const data=conditionCatalog[c.type];if(!data)return '';return `<article class="condition-card"><p class="condition-kind">${esc(data.kind)}</p><h3>${esc(data.name)}</h3><p>${esc(data.front)}</p>${editable?`<div class="condition-actions"><button type="button" onclick="removeCondition(${i},${n})">Сбросить</button></div>`:''}</article>`}
window.addCondition=(i,type)=>{const data=conditionCatalog[type],x=state.investigators[i];if(!data||!canEdit(x))return;x.conditions=x.conditions||[];x.conditions.push({type});logEvent(`${x.name} получает состояние «${data.name}».`);render();conditionModal(i)};
window.removeCondition=(i,n)=>{const x=state.investigators[i];if(!canEdit(x))return;const c=conditionCatalog[x.conditions[n]?.type];x.conditions.splice(n,1);if(c)logEvent(`${x.name} сбрасывает состояние «${c.name}».`);render();conditionModal(i)};
window.saveProcess=i=>{const name=document.querySelector('#p-name').value.trim()||'Безымянный процесс',note=document.querySelector('#p-note').value.trim();if(i>=0){const old=state.processes[i]?.name;state.processes[i]={...state.processes[i],name,note};logEvent(`Активный процесс изменён.`)}else{state.processes.push({name,note,manual:true});logEvent(`Добавлен активный процесс.`)}document.querySelector('#modal').close();render()};window.addProcess=()=>window.saveProcess(-1);window.addLog=()=>{logEvent(document.querySelector('#log-text').value||'Неизвестное событие');document.querySelector('#modal').close();render()};window.applyRest=i=>{const x=state.investigators[i],h=Math.max(0,+document.querySelector('#rest-hp').value),s=Math.max(0,+document.querySelector('#rest-san').value);if(!canEdit(x))return;if(h+s>3)return alert('Можно восстановить не более 3 пунктов суммарно.');x.hp=Math.min(x.hpMax,x.hp+h);x.san=Math.min(x.sanMax,x.san+s);document.querySelector('#modal').close();render()};window.applyTicket=i=>{const x=state.investigators[i],n=Math.max(0,+document.querySelector('#ticket-success').value),k=document.querySelector('#ticket-type').value,room=2-x.train-x.ship;if(!canEdit(x))return;x[k]+=Math.min(n,room);document.querySelector('#modal').close();render()};window.calcCheck=i=>{const x=state.investigators[i],skill=document.querySelector('#check-skill').value,n=Math.max(1,+document.querySelector('#check-base').value+(x.skills[skill]||0)+ +document.querySelector('#check-mod').value+ +document.querySelector('#check-bonus').value+ +document.querySelector('#check-extra').value);document.querySelector('#check-result').innerHTML=`<b>Бросьте ${n} куб.</b><br><span class="subtle">5–6 — успех. Улучшение ${skill}: +${x.skills[skill]||0}.</span>`};window.addItem=i=>{const x=state.investigators[i],v=document.querySelector('#item-name').value.trim();if(!canEdit(x))return;if(v)x.items.push(v);render();inventoryModal(i)};window.removeItem=(i,n)=>{const x=state.investigators[i];if(!canEdit(x))return;x.items.splice(n,1);render();inventoryModal(i)};
document.querySelector('#import-file').addEventListener('change',async e=>{try{state={...structuredClone(base),...JSON.parse(await e.target.files[0].text())};normalizeState();render()}catch{alert('Не удалось прочитать файл партии.')}});
window.chooseInvestigator=i=>{const hero=roster[i];if(!hero||state.investigators.some(x=>x.name===hero.name)||roomCode&&state.investigators.some(x=>x.ownerId===playerId))return;state.investigators.push(newInv(hero));logEvent(`${hero.name} вступает в расследование.`);document.querySelector('#modal').close();render()};
window.claimInvestigator=i=>{const x=state.investigators[i];if(!roomCode||x.ownerId||state.investigators.some(z=>z.ownerId===playerId))return;x.ownerId=playerId;x.ownerName=playerName;render()};
function monsterCard(x,i){const damage=x.hpMax-x.hp,pct=Math.max(0,x.hp/x.hpMax*100),m=[...catalog.monsters,...catalog.epic].find(z=>z.name===x.name)||{};return `<div class="monster-card ${x.hp===0?'defeated':''}"><div class="monster-title"><b>${esc(x.name)}</b><button data-remove-monster="${i}" aria-label="Убрать монстра">×</button></div><div class="monster-location">${esc(x.location)}${x.epic?' · эпический':''}</div><p><b>Воля / ужас:</b> ${esc(m.horror||'—')} · <b>Сила / урон:</b> ${esc(m.combat||'—')}</p><div class="monster-health"><button data-monster-hp="${i}" data-delta="-1" aria-label="Нанести урон">− Урон</button><strong>${x.hp}</strong><span>из ${x.hpMax} HP · получено урона: ${damage}</span><button data-monster-hp="${i}" data-delta="1" aria-label="Вылечить">Лечение +</button></div><div class="monster-hp-bar"><i style="width:${pct}%"></i></div>${x.hp===0?'<b class="monster-defeated">Побеждён — сбросьте жетон</b>':''}${m.effect?`<div class="monster-reckoning"><b>Особый эффект:</b> ${esc(m.effect)}</div>`:''}</div>`}
function monsterPicker(){const list=[...catalog.monsters,...catalog.epic];modal(`<h2>Добавить монстра вручную</h2><p class="subtle">Для наплыва, события или исправления состояния поля.</p><label>Локация<input id="monster-location" placeholder="Например, Рим"></label><div class="catalog-grid monster-picker">${list.map((m,n)=>`<button type="button" onclick="addCatalogMonster(${n})"><b>${esc(m.name)}</b><span>${m.epic?'Эпический · ':''}${monsterMaxHp(m)} здоровья</span></button>`).join('')}</div>`)}
function addMonsterToState(m,location){const spawn=(m.effect||'').match(/(?:Появление|Когда этот монстр выкладывается на поле)[^.:]*[:;,]?\s*(?:поместите|переместить)(?: его)? (?:в|к)\s+([^.;]+)/i),actual=spawn?spawn[1].trim():location,hp=monsterMaxHp(m);state.monsters.push({name:m.name,location:actual,hp,hpMax:hp,epic:m.epic,reckoning:/расплат/i.test(m.effect||'')?m.effect:''});return actual}
window.addCatalogMonster=n=>{const list=[...catalog.monsters,...catalog.epic],m=list[n],location=document.querySelector('#monster-location').value.trim();if(!m)return;if(!location)return alert('Сначала укажите локацию монстра.');const actual=addMonsterToState(m,location);logEvent(`Появился монстр ${m.name} в локации ${actual}.`);document.querySelector('#modal').close();render()};
function renderRoomStatus(){const status=document.querySelector('#room-status'),code=document.querySelector('#room-code'),button=document.querySelector('.room-button');if(!status)return;if(location.protocol==='file:'){status.textContent='Нужна опубликованная версия';code.textContent='Общая комната';button.classList.remove('online');return}status.textContent=roomCode?'Синхронизация включена':'Локальная партия';code.textContent=roomCode?`Комната ${roomCode}`:'Общая комната';button.classList.toggle('online',!!roomCode)}
function openRoomModal(){if(location.protocol==='file:'){modal('<h2>Общая комната</h2><p>Режим комнаты работает на опубликованном сайте. Откройте общую ссылку на всех телефонах — локальный файл продолжит работать только на одном устройстве.</p>');return}modal(roomCode?`<h2>Комната ${roomCode}</h2><p>Все телефоны с этим кодом видят одну партию. Изменения синхронизируются автоматически.</p><div class="sync-note">Передайте игрокам адрес этого сайта и код <b>${roomCode}</b>.</div><div class="form-stack"><button class="ghost" type="button" onclick="leaveRoom()">Выйти из комнаты</button></div>`:'<h2>Общая комната</h2><p>Создайте комнату из текущей партии или войдите в уже созданную.</p><div class="room-choice"><button class="primary" type="button" onclick="createRoom()">Создать комнату</button><button class="ghost" type="button" onclick="showJoinRoom()">Войти по коду</button></div>')}
window.showJoinRoom=()=>modal('<h2>Войти в комнату</h2><div class="form-stack"><input class="room-code-input" id="join-code" maxlength="6" autocomplete="off" placeholder="ABC123"><button class="primary" type="button" onclick="joinRoom()">Войти</button></div>');
window.createRoom=async()=>{try{const r=await fetch('/api/rooms',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({state})});if(!r.ok)throw new Error();const data=await r.json();roomCode=data.code;remoteUpdatedAt=data.updatedAt||0;localStorage.setItem('eh-room-code',roomCode);document.querySelector('#modal').close();renderRoomStatus()}catch{alert('Не удалось создать комнату. Проверьте интернет и попробуйте снова.')}};
window.joinRoom=async()=>{const code=document.querySelector('#join-code').value.trim().toUpperCase();try{const r=await fetch('/api/rooms/'+encodeURIComponent(code));if(r.status===404)return alert('Комната с таким кодом не найдена.');if(!r.ok)throw new Error();const data=await r.json();roomCode=code;remoteUpdatedAt=data.updatedAt||0;localStorage.setItem('eh-room-code',roomCode);applyingRemote=true;state={...structuredClone(base),...data.state};normalizeState();render();applyingRemote=false;document.querySelector('#modal').close();renderRoomStatus()}catch{alert('Не удалось войти в комнату. Проверьте интернет.')}};
window.leaveRoom=()=>{roomCode='';remoteUpdatedAt=0;localStorage.removeItem('eh-room-code');document.querySelector('#modal').close();renderRoomStatus()};
async function pushRoom(){if(!roomCode)return;try{const r=await fetch('/api/rooms/'+encodeURIComponent(roomCode),{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({state,baseUpdatedAt:remoteUpdatedAt})});if(r.status===409){await pullRoom();return}if(!r.ok)throw new Error();const data=await r.json();remoteUpdatedAt=data.updatedAt||remoteUpdatedAt;renderRoomStatus()}catch{document.querySelector('#room-status').textContent='Нет связи · сохранено локально'}}
async function pullRoom(){if(!roomCode||document.hidden)return;try{const r=await fetch('/api/rooms/'+encodeURIComponent(roomCode));if(r.status===404){roomCode='';localStorage.removeItem('eh-room-code');renderRoomStatus();return}if(!r.ok)return;const data=await r.json();if((data.updatedAt||0)>remoteUpdatedAt){remoteUpdatedAt=data.updatedAt;applyingRemote=true;state={...structuredClone(base),...data.state};normalizeState();render();applyingRemote=false}}catch{}}
renderRules();render();
if(!window.FIREBASE_ROOM_MODE){
  if(roomCode&&location.protocol!=='file:')pullRoom();
  setInterval(pullRoom,2000);
}
