(function(){
'use strict';
const C=window.GAME_CATALOG||{},MYTH=window.MYTHOS_CARDS||[],SKILLS=['Знание','Общение','Внимание','Сила','Воля'];
const LOCATIONS=['Аркхэм (локация 1)','Лондон (локация 2)','Рим (локация 3)','Стамбул (локация 4)','Гималаи (локация 5)','Токио (локация 6)','Сан-Франциско (локация 7)','Буэнос-Айрес (локация 8)','Антарктида (локация 9)','Тунгуска (локация 10)','Амазония (локация 11)','Сидней (локация 12)','Шанхай (локация 13)','Пирамиды (локация 14)','Сердце Африки (локация 15)','Сибирь (локация 16)','Иной мир'];
const CHAPTERS=[
 {title:'Шёпот под водой',intro:'В портовых городах находят лодки без экипажа. На мокрых палубах остаются следы, похожие на письмена, а моряки во сне слышат зов из глубин.',end:'Зов отступает, но океан ещё долго хранит имена тех, кто посмотрел в его бездну.',need:{clues:3,gates:1,cities:2}},
 {title:'Звёзды меняют путь',intro:'Небо перестаёт подчиняться астрономам. Старые карты ведут к новым берегам, а в избранных городах часы начинают идти назад.',end:'Созвездия возвращаются на свои места, оставляя над миром тонкий шрам из холодного света.',need:{clues:4,gates:2,cities:2}},
 {title:'Поднимающийся Р’льех',intro:'Из моря поднимаются чёрные шпили. Каждая волна приносит обрывки чужих воспоминаний, и имя Ктулху уже невозможно забыть.',end:'Р’льех вновь уходит под воду. Победа не стирает увиденного — она лишь даёт миру ещё одну ночь.',need:{clues:5,gates:2,cities:2}}
];
const SPECIAL=LOCATIONS.slice(0,16);
const $=s=>document.querySelector(s),clone=x=>structuredClone(x),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID(),now=()=>Date.now();let screen='entry',tab='party',roomCode='',me={uid:'',deviceId:RoomAPI.deviceId},menu=false,syncing=false;
function fresh(){return {version:5,meta:{mode:'solo',hostUid:'',cohostUid:'',started:false,status:'lobby',round:1,phase:'Действия'},world:{doom:12,omen:'зелёное',gates:[],clues:[],monsters:[],rumors:[],processes:[]},campaign:{chapter:0,stage:'checklist',cities:[],clues:0,gates:0,bosses:[],currentBoss:null,storyOpen:true,mythDeck:buildMythDeck(),mythIndex:-1,mythStep:0,mythApplied:[]},players:{},log:[],undo:[],settings:{sound:false}}}
let state=normalize(loadLocal()||fresh());
function normalize(s){const f=fresh();s={...f,...(s||{})};s.meta={...f.meta,...(s.meta||{})};s.world={...f.world,...(s.world||{})};s.campaign={...f.campaign,...(s.campaign||{})};for(const k of ['gates','clues','monsters','rumors','processes'])if(!Array.isArray(s.world[k]))s.world[k]=[];for(const k of ['cities','bosses','mythDeck','mythApplied'])if(!Array.isArray(s.campaign[k]))s.campaign[k]=[];if(!s.campaign.mythDeck.length)s.campaign.mythDeck=buildMythDeck();s.players=s.players||{};s.log=Array.isArray(s.log)?s.log:[];s.undo=Array.isArray(s.undo)?s.undo:[];Object.values(s.players).forEach(p=>{p.assets=p.assets||[];p.unique=p.unique||[];p.spells=p.spells||[];p.conditions=p.conditions||[];p.skillMods=p.skillMods||{};p.stats=p.stats||{clues:0,cities:0,damage:0,kills:0,luck:0}});return s}
function buildMythDeck(){const colors={green:4,yellow:9,blue:2},deck=[];for(const [color,n] of Object.entries(colors)){const pool=MYTH.filter(x=>x.color===color);for(let i=0;i<n&&pool.length;i++)deck.push(pool[Math.floor(Math.random()*pool.length)].id)}return deck.sort(()=>Math.random()-.5)}
function loadLocal(){try{return JSON.parse(localStorage.getItem('eh-v05-state'))}catch{return null}}
function saveLocal(){localStorage.setItem('eh-v05-state',JSON.stringify(state))}
function player(){return Object.values(state.players).find(p=>p.ownerUid===me.uid&&p.deviceId===me.deviceId)||null}
function host(){return state.meta.hostUid===me.uid}function cohost(){return state.meta.cohostUid===me.uid}function leads(){return host()||cohost()||state.meta.mode==='solo'}
function inv(id){return C.investigators?.find(x=>x.id===id)}function myInv(){return inv(player()?.investigatorId)}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function modal(html){$('#modal-body').innerHTML=`<div class="modal-head"><h2>${html.title||''}</h2><button class="ghost small" onclick="App.closeModal()">Закрыть</button></div>${html.body||''}`;$('#modal').showModal()}
function closeModal(){try{$('#modal').close()}catch{}}
function log(kind,text,details=''){state.log.unshift({id:uid(),at:now(),kind,text,details,by:player()?.name||'Ведущий'});state.log=state.log.slice(0,250)}
function snapshot(){state.undo.unshift({at:now(),world:clone(state.world),campaign:clone(state.campaign),players:clone(state.players)});state.undo=state.undo.slice(0,12)}
async function commit(label=''){saveLocal();render();if(label)log('technical',label);if(roomCode&&!syncing){try{await RoomAPI.update(roomCode,{world:state.world,campaign:state.campaign,players:state.players,log:state.log,undo:state.undo,'meta/round':state.meta.round,'meta/phase':state.meta.phase,'meta/started':state.meta.started,'meta/status':state.meta.status,'meta/cohostUid':state.meta.cohostUid})}catch{toast('Нет связи · сохранено на телефоне')}}}
function mergeRoom(r){syncing=true;state=normalize({...state,...r,meta:{...state.meta,...r.meta},settings:state.settings});saveLocal();render();syncing=false}
async function boot(){me=await RoomAPI.identity();const saved=localStorage.getItem('eh-v05-room');if(saved&&RoomAPI.configured()){try{const joined=await RoomAPI.join(saved);roomCode=joined.code;mergeRoom(joined.room);screen='game';RoomAPI.watch(roomCode,mergeRoom)}catch{localStorage.removeItem('eh-v05-room')}}render()}
function render(){const app=$('#app');if(screen==='entry')return app.innerHTML=entry();app.innerHTML=`<div class="app-shell">${topbar()}<main>${tab==='party'?party():tab==='investigator'?investigator():tab==='contact'?contact():tab==='myth'?myth():world()}</main>${nav()}</div>`}
function entry(){return `<section class="splash"><div class="hero"><div class="eyebrow">Streamlined v0.5</div><h1>Хроники<br>Древнего Ужаса</h1><p class="lead">Мир ещё не знает, что спит под чёрной водой. Выберите, будете ли вы хранить эту историю в одиночку — или разделите её с другими сыщиками.</p><div class="grid two"><button class="primary" onclick="App.solo()">Начать одиночную партию</button><button onclick="App.roomDialog()">Общая комната</button></div><p class="muted" style="margin-top:16px">Ктулху · три главы · физические кубики и контакты</p></div></section>`}
function topbar(){return `<header class="topbar"><div class="brand"><button class="sigil" onclick="App.cthulhu()">☊</button><div><strong>${esc(CHAPTERS[state.campaign.chapter]?.title||'Хроника завершена')}</strong><small>${state.meta.phase} · раунд ${state.meta.round}</small></div></div><button class="room-pill" onclick="App.toggleMenu()">${roomCode?'Комната '+roomCode:'Одиночная партия'} · ⋯</button>${menu?hostMenu():''}</header>`}
function hostMenu(){return `<div class="menu stack"><b>Меню ${leads()?'ведущего':'игрока'}</b><button onclick="App.chronicle(true)">Открыть летопись</button>${host()?`<button onclick="App.assignCohost()">Назначить соведущего</button><button onclick="App.transferHost()">Передать роль ведущего</button><button onclick="App.undo()">Отменить последнюю операцию</button><button class="danger" onclick="App.resetDialog()">Сбросить партию</button>`:''}<button class="ghost" onclick="App.leave()">Выйти на заставку</button></div>`}
function nav(){return `<nav class="nav">${[['party','⌂','Партия'],['investigator','♙','Сыщик'],['contact','✦','Контакт'],['myth','☾','Миф'],['world','◎','Мир']].map(([id,ic,n])=>`<button class="${tab===id?'active':''}" onclick="App.go('${id}')"><span>${ic}</span>${n}</button>`).join('')}</nav>`}
function party(){const ch=CHAPTERS[state.campaign.chapter];if(!ch)return finale();const ps=Object.values(state.players),ready=ps.filter(p=>p.ready).length,boss=state.campaign.currentBoss;return `<section class="hero"><div class="eyebrow">Глава ${state.campaign.chapter+1} из 3</div><h1>${esc(ch.title)}</h1>${state.campaign.storyOpen?`<p class="story">${esc(ch.intro)}</p><button class="ghost small" onclick="App.collapseStory()">Свернуть вступление</button>`:`<button class="ghost small" onclick="App.collapseStory()">Прочитать вступление снова</button>`}</section>${boss?`<div class="section-title"><h2>Развязка главы</h2></div><div class="card"><div class="eyebrow">Босс · ${esc(boss.location)}</div><h2>${esc(boss.name)}</h2><div class="stat"><b>${boss.hp}/${boss.maxHp}</b>здоровье</div>${leads()?'<button class="primary" onclick="App.completeBoss()">Завершить битву и главу</button>':''}</div>`:`<div class="section-title"><h2>Что приближает развязку</h2><span class="muted">Босс пока скрыт</span></div>${checklist(ch)}${state.campaign.stage==='preparation'?`<div class="notice">Чек-лист завершён. Сыщики получают одну фазу подготовки.${leads()?' После неё откройте внезапную развязку.':''}</div>${leads()?'<button class="primary" style="width:100%;margin-top:10px" onclick="App.revealBoss()">Завершить подготовку</button>':''}`:''}`}<div class="section-title"><h2>Экспедиция</h2><span class="muted">${ready}/${ps.length} готовы</span></div><div class="grid two">${ps.length?ps.map(playerCard).join(''):'<div class="card empty">Сначала выберите сыщика.</div>'}</div>${leads()?`<div class="section-title"><h2>Управление фазой</h2></div><div class="card stack"><div class="row wrap">${['Действия','Контакты','Миф'].map(x=>`<button class="${state.meta.phase===x?'primary':''}" onclick="App.setPhase('${x}')">${x}</button>`).join('')}</div><button onclick="App.nextRound()">Завершить раунд</button></div>`:''}`}
function checklist(ch){const c=state.campaign;return `<div class="grid two"><div class="card"><h3>Собрать улики</h3><div class="stats"><div class="stat"><b>${c.clues}/${ch.need.clues}</b>контактов</div></div><button class="small" onclick="App.bumpCampaign('clues')">Отметить улику</button></div><div class="card"><h3>Закрыть врата</h3><div class="stats"><div class="stat"><b>${c.gates}/${ch.need.gates}</b>врат</div></div><button class="small" onclick="App.bumpCampaign('gates')">Отметить врата</button></div><div class="card" style="grid-column:1/-1"><h3>Исследовать особые города</h3><div class="chips">${c.cities.map(x=>`<span class="chip good">${esc(x)}</span>`).join('')||'<span class="muted">Города ещё не исследованы</span>'}</div><button class="small" onclick="App.addCity()">Добавить город</button></div></div>`}
function playerCard(p){const i=inv(p.investigatorId);return `<article class="card"><div class="row"><div class="portrait">${esc(i?.name?.[0]||'?')}</div><div><h3 style="margin:0">${esc(i?.name||p.name)}</h3><span class="muted">${p.online===false?'не в сети':p.ready?'готов':'в игре'}</span></div></div><div class="stats" style="margin-top:12px"><div class="stat"><b>${p.hp}/${i?.hp||0}</b>HP</div><div class="stat"><b>${p.san}/${i?.san||0}</b>SAN</div><div class="stat"><b>${p.clues||0}</b>улики</div><div class="stat"><b>${(p.train||0)+(p.ship||0)}</b>билеты</div></div></article>`}
function investigator(){const p=player(),i=myInv();if(!p||!i)return chooseInvestigator();return `<div class="hero"><div class="eyebrow">${esc(i.role)}</div><h1>${esc(i.name)}</h1><p class="lead">${esc(i.ability)}</p><div class="chips"><span class="chip">Реакция · ${esc(i.reaction)}</span></div></div><div class="section-title"><h2>Состояние</h2><button class="small ${p.ready?'primary':''}" onclick="App.toggleReady()">${p.ready?'Готов к следующей фазе':'Завершить действия'}</button></div><div class="card"><div class="stats"><button class="stat" onclick="App.counter('hp')"><b>${p.hp}/${i.hp}</b>HP</button><button class="stat" onclick="App.counter('san')"><b>${p.san}/${i.san}</b>SAN</button><button class="stat" onclick="App.counter('clues')"><b>${p.clues}</b>улики</button><button class="stat" onclick="App.tickets()"><b>${p.train||0} / ${p.ship||0}</b>поезд / корабль</button></div></div><div class="section-title"><h2>Навыки</h2><button class="small" onclick="App.rest()">Отдых · 2 пункта</button></div><div class="card">${SKILLS.map(s=>`<div class="skill-row"><span>${s}</span><span class="muted">база ${i.skills[s]}</span><button class="small" onclick="App.skill('${s}')">${(p.skillMods?.[s]||0)>=0?'+':''}${p.skillMods?.[s]||0}</button></div>`).join('')}</div>${inventory(p)}`}
function chooseInvestigator(){return `<section class="hero"><div class="eyebrow">Досье экспедиции</div><h1>Выберите сыщика</h1><p class="lead">Этот телефон будет управлять одним героем. До начала истории выбор можно изменить свободно.</p></section><div class="grid investigator-list" style="margin-top:16px">${C.investigators.map(i=>`<button class="card" onclick="App.choose('${i.id}')"><h3>${esc(i.name)}</h3><p class="muted">${esc(i.role)}</p><div class="stats"><div class="stat"><b>${i.hp}</b>HP</div><div class="stat"><b>${i.san}</b>SAN</div></div></button>`).join('')}</div>`}
function inventory(p){const all=[...(p.assets||[]),...(p.unique||[]),...(p.spells||[]),...(p.conditions||[])];return `<div class="section-title"><h2>Способности и имущество</h2><button class="small" onclick="App.addInventory()">Добавить</button></div><div class="grid two">${all.length?all.map(itemCard).join(''):'<div class="card empty">Пока ничего нет.</div>'}</div>`}
function itemCard(id){const x=[...(C.assets||[]),...(C.unique||[]),...(C.spells||[]),...(C.conditions||[])].find(v=>v.id===id);return `<article class="card"><div class="eyebrow">${esc(x?.timing||x?.type||'Имущество')}</div><h3>${esc(x?.name||id)}</h3><p>${esc(x?.text||x?.effect||'')}</p>${x?.check?`<span class="chip">${esc(x.check)}</span>`:''}</article>`}
function contact(){const p=player();if(!p)return chooseInvestigator();return `<section class="hero"><div class="eyebrow">Фаза контактов</div><h1>Что встретилось вам?</h1><p class="lead">Назовите место только сейчас. Приложение сначала проверит монстров, затем проведёт через бой или поможет записать результат физической карты контакта.</p></section><div class="grid two" style="margin-top:16px"><button class="card" onclick="App.startCombat()"><h2>Боевой контакт</h2><p>Выбрать место и всех монстров, пройти Волю и Силу отдельными шагами.</p></button><button class="card" onclick="App.contactResult()"><h2>Обычный контакт</h2><p>Разыграйте физическую карту, затем пошагово внесите всё полученное и потерянное.</p></button><button class="card" onclick="App.clueContact()"><h2>Контакт с уликой</h2><p>Записать результат и обновить личную историю и цель главы.</p></button><button class="card" onclick="App.trade()"><h2>Обмен</h2><p>Отдельное действие с подтверждением общей локации.</p></button></div>`}
function myth(){const card=MYTH.find(x=>x.id===state.campaign.mythDeck[state.campaign.mythIndex]);if(!card)return `<section class="hero"><div class="eyebrow">Фаза Мифа</div><h1>Мир замирает</h1><p class="lead">Следующая карта уже лежит в колоде, но её содержание скрыто. Только ведущий может открыть новую главу бедствия.</p>${leads()?'<button class="primary" onclick="App.drawMyth()">Вытянуть карту Мифа</button>':'<div class="notice">Ожидаем ведущего.</div>'}</section>`;const steps=mythSteps(card),at=state.campaign.mythStep;return `<section class="hero"><div class="eyebrow">${esc(card.category)} · ${esc(card.color)}</div><h1>${esc(card.title)}</h1><p class="story">${esc(card.story)}</p></section><div class="section-title"><h2>Событие ${Math.min(at+1,steps.length)} из ${steps.length}</h2><span class="muted">Будущее скрыто</span></div><div class="card"><div class="eyebrow">${at===0?'Вступление':'Сейчас происходит'}</div><h2>${esc(steps[at]?.title||'Итог')}</h2><p class="story">${esc(steps[at]?.story||'Мир запомнил последствия этого события.')}</p>${steps[at]?`<div class="notice"><b>Что сделать сейчас</b><br>${esc(steps[at].action)}</div>`:''}<div class="row wrap" style="margin-top:14px">${leads()&&steps[at]?'<button class="primary" onclick="App.applyMythStep()">Выполнено · дальше</button>':''}${leads()&&at>=steps.length?'<button onclick="App.finishMyth()">Завершить фазу Мифа</button>':''}</div></div><details class="card" style="margin-top:14px"><summary>Посмотреть напечатанный текст карты</summary><p>${esc(card.effect)}</p>${card.reckoning?`<p><b>Расплата:</b> ${esc(card.reckoning)}</p>`:''}</details>`}
function mythSteps(card){const arr=[{title:'Тревожное предчувствие',story:card.story,action:'Прочитайте вступление и ничего не меняйте.'}];for(const icon of card.icons||[]){if(icon==='clue')arr.push({type:'clue',title:'Свидетельства со всего мира',story:'По миру расходятся рассказы о невозможном. В одних местах видели свет под землёй, в других — тени, которые не принадлежали людям.',action:'Вытяните нужное число жетонов улик и укажите их локации.'});else if(icon==='gate')arr.push({type:'gate',title:'Ткань мира рвётся',story:'Воздух становится тонким, и сквозь него проступают чужие созвездия. Там, где возник разлом, уже слышно движение.',action:'Вытяните жетон врат, укажите локацию и появившегося монстра.'});else if(icon==='monster')arr.push({type:'monster',title:'Из тьмы выходят чудовища',story:'Из пустых переулков и забытых тоннелей приходят существа, которым нет места в человеческом мире.',action:'Вытяните монстров и укажите их локации.'});else if(icon==='omen')arr.push({type:'omen',title:'Знамение меняется',story:'Небо поворачивается, словно огромный механизм. Открытые врата откликаются на новый знак.',action:'Передвиньте знамение. Приложение подсчитает совпавшие врата.'});else if(icon==='reckoning')arr.push({type:'reckoning',title:'Наступает расплата',story:'Всё, что мир откладывал на потом, требует платы одновременно. Долги, состояния, слухи и чудовища приходят в движение.',action:'Проверьте отмеченные расплатой состояния, имущество, слухи и монстров.'});else if(icon==='surge')arr.push({type:'surge',title:'Наплыв чудовищ',story:'Разломы исторгают новых тварей. Они идут туда, где граница мира уже слабее всего.',action:'Приложение покажет врата для наплыва и число монстров.'})}if(card.effect||card.tokens)arr.push({type:'effect',title:'Угроза остаётся в мире',story:literaryEffect(card),action:card.effect||card.automation||'Примените текст карты.'});return arr}
function literaryEffect(card){if(card.tokens)return `Событие «${card.title}» укореняется в мире. Время теперь измеряется не часами, а исчезающими знаками Древних.`;if(card.category?.toLowerCase().includes('слух'))return `Слух о событии «${card.title}» перестаёт быть шёпотом. Теперь его последствия может увидеть каждый.`;return `Событие «${card.title}» меняет привычный порядок вещей. Экспедиции придётся жить с его последствиями.`}
function world(){return `<section class="hero"><div class="eyebrow">Состояние мира</div><h1>Угрозы и хроника</h1><div class="stats"><div class="stat"><b>${state.world.doom}</b>безысходность</div><div class="stat"><b>${state.world.gates.length}</b>врата</div><div class="stat"><b>${state.world.clues.length}</b>улики</div><div class="stat"><b>${state.world.monsters.length}</b>монстры</div></div></section><div class="section-title"><h2>Врата и улики</h2><div class="row"><button class="small" onclick="App.addGate()">+ Врата</button><button class="small" onclick="App.addFieldClue()">+ Улика</button></div></div><div class="grid two">${state.world.gates.map(g=>objectCard(g,'Врата')).join('')}${state.world.clues.map(c=>objectCard(c,'Улика')).join('')||'<div class="card empty">На поле пока ничего не отмечено.</div>'}</div><div class="section-title"><h2>Монстры</h2><button class="small" onclick="App.addMonster()">Добавить вручную</button></div><div class="grid two">${state.world.monsters.length?state.world.monsters.map(monsterCard).join(''):'<div class="card empty">Монстров в приложении нет.</div>'}</div><div class="section-title"><h2>Слухи и процессы</h2></div><div class="grid">${[...state.world.rumors,...state.world.processes].length?[...state.world.rumors,...state.world.processes].map(processCard).join(''):'<div class="card empty">Активных процессов нет.</div>'}</div><div class="section-title"><h2>Хроника</h2><button class="small" onclick="App.addMemory()">Добавить памятный момент</button></div>${chronicle(false)}`}
function objectCard(x,type){return `<article class="card"><div class="eyebrow">${type}</div><h3>${esc(x.location)}</h3>${x.symbol?`<span class="chip">${esc(x.symbol)}</span>`:''}<button class="ghost small" onclick="App.removeWorld('${x.id}')">Убрать</button></article>`}
function monsterCard(x){const m=[...(C.monsters||[]),...(C.epic||[])].find(a=>a.id===x.catalogId)||{};return `<article class="card monster"><div><div class="eyebrow">${x.boss?'Эпический монстр':'Монстр'} · ${esc(x.location)}</div><h3>${esc(m.name||x.name)}</h3><div class="chips"><span class="chip">Воля ${esc(m.horror||'—')}</span><span class="chip">Сила ${esc(m.combat||'—')}</span></div><p class="muted">${esc(m.effect||'')}</p></div><div><div class="stat"><b>${x.hp}</b>HP</div><button class="small" onclick="App.hurtMonster('${x.id}')">−1 HP</button></div></article>`}
function processCard(x){return `<article class="card"><div class="eyebrow">${x.kind||'Процесс'}</div><h3>${esc(x.title)}</h3><p>${esc(x.text||'')}</p><div class="chips"><span class="chip">Жетоны: ${x.tokens||0}</span><button class="small" onclick="App.resolveProcess('${x.id}')">Разрешить</button></div></article>`}
function chronicle(full){const entries=state.log.filter(x=>full||x.kind!=='technical');return `${full?'<div class="stack">':''}${entries.slice(0,full?250:8).map(x=>`<article class="card"><div class="eyebrow">${new Date(x.at).toLocaleString('ru')} · ${esc(x.by)}</div><p style="margin:6px 0 0">${esc(x.text)}</p>${x.details?`<details><summary>Технические изменения</summary><p>${esc(x.details)}</p></details>`:''}</article>`).join('')||'<div class="card empty">История ещё не началась.</div>'}${full?'</div>':''}`}
function finale(){return `<section class="hero"><div class="eyebrow">Финал хроники</div><h1>Море вновь стало тихим</h1><p class="story">${epilogue()}</p></section>${chronicle(false)}`}
function epilogue(){const ps=Object.values(state.players),dead=ps.filter(p=>p.eliminated),heroes=ps.filter(p=>!p.eliminated);return `Когда Р’льех исчез под водой, ${heroes.map(p=>inv(p.investigatorId)?.name).filter(Boolean).join(', ')||'никто из экспедиции'} ещё долго не решались назвать случившееся победой. ${dead.length?`Имена ${dead.map(p=>inv(p.investigatorId)?.name).join(', ')} остались в записях тех, кто вернулся.`:'Все вернулись — хотя прежними не остались.'} Мир выжил с безысходностью ${state.world.doom}, запомнив ${state.campaign.clues} найденных зацепок и ${state.campaign.gates} закрытых разломов.`}
async function solo(){state=fresh();state.meta.mode='solo';state.meta.hostUid=me.uid;screen='game';log('story','Экспедиция собралась втайне от мира. Пока её единственный участник ещё не знает, кто откликнется на зов.');commit()}
function roomDialog(){modal({title:'Общая комната',body:`<div class="stack"><button class="primary" onclick="App.createRoom()">Создать новую комнату</button><div class="field"><label>Код комнаты</label><input id="join-code" maxlength="6" autocomplete="off" placeholder="ABC234"></div><button onclick="App.joinRoom()">Войти по коду</button>${!RoomAPI.configured()?'<div class="notice">В этой копии сайта ещё не заполнен firebase-config.js. В опубликованном репозитории сохраните уже настроенный файл.</div>':''}</div>`})}
async function createRoom(){try{state=fresh();state.meta.mode='room';state.meta.hostUid=me.uid;const out=await RoomAPI.create(state);roomCode=out.code;state={...state,...out.room,meta:{...state.meta,...out.room.meta}};closeModal();screen='game';RoomAPI.watch(roomCode,mergeRoom);log('story','В шести знаках кода комнаты была запечатана новая хроника.');commit();toast(`Комната ${roomCode} создана`)}catch(e){toast(e.message)}}
async function joinRoom(){try{const out=await RoomAPI.join($('#join-code').value);roomCode=out.code;state={...state,...out.room,meta:{...state.meta,...out.room.meta}};closeModal();screen='game';RoomAPI.watch(roomCode,mergeRoom);toast(`Вы в комнате ${roomCode}`);render()}catch(e){toast(e.message)}}
function leave(){RoomAPI.stop();roomCode='';localStorage.removeItem('eh-v05-room');screen='entry';menu=false;render()}
function toggleMenu(){menu=!menu;render()}function go(x){tab=x;menu=false;render()}
function collapseStory(){state.campaign.storyOpen=!state.campaign.storyOpen;commit()}
function cthulhu(){modal({title:'Ктулху · Безумие из глубин',body:`<p class="story">Входя в локацию с жетоном Древних, сыщик теряет 1 рассудок. В морской локации с жетоном Древних сыщик также задержан — задержку контролируйте физически.</p><div class="notice">Если разгаданы три тайны, сыщики побеждают. При пробуждении Ктулху откройте его финальный сценарий.</div>`})}
async function choose(id){if(state.meta.started&&player()?.investigatorId&&!player()?.eliminated)return toast('После начала смена возможна только при выбытии героя');const i=inv(id),key=player()?.id||uid(),late=state.meta.started;state.players[key]={...(state.players[key]||{}),id:key,ownerUid:me.uid,deviceId:me.deviceId,name:i.name,investigatorId:id,hp:i.hp,san:i.san,clues:startingClues(i),train:0,ship:0,skillMods:{},assets:startingIds(i,'assets'),unique:startingIds(i,'unique'),spells:startingIds(i,'spells'),conditions:[],ready:false,online:true,eliminated:false,stats:{clues:0,cities:0,damage:0,kills:0,luck:0}};log('story',late?`На следующее утро расследование пополнилось новым участником — ${i.name}.`:`${i.name} принял приглашение и присоединился к экспедиции.`);commit()}
function startingClues(i){const m=i.starting?.match(/(\d+)\s*улик/iu);return m?Number(m[1]):0}function startingIds(i,type){const text=(i.starting||'').toLowerCase(),pool=C[type]||[];return pool.filter(x=>text.includes(x.name.toLowerCase())).map(x=>x.id)}
function toggleReady(){const p=player();p.ready=!p.ready;log('technical',`${p.name}: ${p.ready?'готов':'снял готовность'}`);commit()}
function setPhase(x){if(!leads())return;const unready=Object.values(state.players).filter(p=>!p.ready);if(unready.length&&!confirm(`${unready.length} игроков не отметили готовность. Перейти всё равно?`))return;snapshot();state.meta.started=true;state.meta.phase=x;Object.values(state.players).forEach(p=>p.ready=false);log('story',x==='Миф'?'Последние разговоры стихают. Мир отвечает экспедиции новым бедствием.':`Начинается фаза «${x}».`);commit('Смена фазы')}
function nextRound(){snapshot();state.meta.round++;state.meta.phase='Действия';Object.values(state.players).forEach(p=>p.ready=false);log('story',`Наступает ${state.meta.round}-й раунд. Сыщики получают короткую передышку перед новым ударом.`);commit('Новый раунд')}
function counter(k){const p=player(),i=myInv(),max=k==='hp'?i.hp:k==='san'?i.san:99;modal({title:k==='hp'?'Здоровье':k==='san'?'Рассудок':'Улики',body:`<div class="row"><button onclick="App.changeCounter('${k}',-1)">−</button><div class="stat" style="flex:1"><b>${p[k]}</b>сейчас</div><button onclick="App.changeCounter('${k}',1,${max})">+</button></div>`})}
function changeCounter(k,d,max=99){const p=player();p[k]=Math.max(0,Math.min(max,p[k]+d));if((k==='hp'||k==='san')&&p[k]===0){p.eliminated=true;log('story',`${p.name} выбыл из экспедиции, но его судьба останется частью этой хроники.`)}commit();counter(k)}
function tickets(){const p=player();modal({title:'Билеты',body:`<p>Получение билетов — действие в городе: проверка Общения, один успех даёт один подходящий билет, максимум два суммарно.</p><div class="grid two"><button onclick="App.ticket('train')">Поезд: ${p.train||0}</button><button onclick="App.ticket('ship')">Корабль: ${p.ship||0}</button></div>`})}
function ticket(k){const p=player(),other=k==='train'?'ship':'train';if((p[k]||0)+(p[other]||0)>=2)return toast('Максимум два билета');p[k]=(p[k]||0)+1;commit();tickets()}
function skill(s){const p=player();p.skillMods[s]=(p.skillMods[s]||0)+1;if(p.skillMods[s]>2)p.skillMods[s]=-2;log('technical',`${p.name}: модификатор навыка ${s} теперь ${p.skillMods[s]}`);commit()}
function rest(){const p=player(),i=myInv();modal({title:'Отдых · распределить 2 пункта',body:`<p>Выберите восстановление. Суммарно можно вернуть два пункта здоровья и/или рассудка.</p><div class="grid two"><button onclick="App.applyRest(2,0)">+2 HP</button><button onclick="App.applyRest(1,1)">+1 HP, +1 SAN</button><button onclick="App.applyRest(0,2)">+2 SAN</button></div>`})}
function applyRest(h,s){const p=player(),i=myInv();p.hp=Math.min(i.hp,p.hp+h);p.san=Math.min(i.san,p.san+s);log('story',`${p.name} нашёл время перевязать раны и привести мысли в порядок.`);closeModal();commit()}
function addInventory(){const groups=[['assets','Обычные вещи'],['unique','Уникальные вещи'],['spells','Заклинания'],['conditions','Состояния']];modal({title:'Добавить в карточку',body:groups.map(([k,n])=>`<button style="width:100%;margin-bottom:8px" onclick="App.pickInventory('${k}')">${n}</button>`).join('')})}
function pickInventory(k){const p=player(),pool=C[k]||[];modal({title:'Поиск',body:`<div class="field"><input id="catalog-search" placeholder="Начните вводить название" oninput="App.filterCatalog('${k}')"></div><div id="catalog-list" class="stack" style="margin-top:12px">${catalogButtons(pool,k,p)}</div>`})}
function catalogButtons(pool,k,p){return pool.map(x=>`<button class="card" data-search="${esc(x.name.toLowerCase())}" onclick="App.takeItem('${k}','${x.id}')"><b>${esc(x.name)}</b><br><span class="muted">${esc(x.timing||x.type||'вещь')} · ${esc(x.text||x.effect||'')}</span></button>`).join('')}
function filterCatalog(){const q=$('#catalog-search').value.toLowerCase();document.querySelectorAll('[data-search]').forEach(x=>x.hidden=!x.dataset.search.includes(q))}
function takeItem(k,id){const p=player();p[k]=p[k]||[];if(!p[k].includes(id))p[k].push(id);log('story',`${p.name} получает «${[...(C[k]||[])].find(x=>x.id===id)?.name||id}».`);closeModal();commit()}
function startCombat(){modal({title:'Где начинается бой?',body:`<div class="field"><label>Текущая локация сыщика</label><select id="combat-loc">${LOCATIONS.map(x=>`<option>${x}</option>`).join('')}</select></div><button class="primary" style="width:100%;margin-top:12px" onclick="App.chooseCombatMonsters()">Найти монстров</button>`})}
function chooseCombatMonsters(){const loc=$('#combat-loc').value,ms=state.world.monsters.filter(x=>x.location===loc);if(!ms.length)return toast('В этой локации монстры не отмечены');modal({title:'Порядок боя',body:`<p>Нажимайте монстров в том порядке, в котором хотите сражаться.</p>${ms.map(x=>`<button class="card" style="width:100%;margin-bottom:8px" onclick="App.combatWizard('${x.id}')">${esc(([...(C.monsters||[]),...(C.epic||[])].find(m=>m.id===x.catalogId)?.name)||x.name)} · ${x.hp} HP</button>`).join('')}`})}
function combatWizard(id){const x=state.world.monsters.find(x=>x.id===id),m=[...(C.monsters||[]),...(C.epic||[])].find(a=>a.id===x.catalogId),p=player(),i=myInv(),will=i.skills['Воля']+(p.skillMods?.['Воля']||0),strength=i.skills['Сила']+(p.skillMods?.['Сила']||0);modal({title:`Бой · ${m.name}`,body:`<div class="steps"><div class="step"><h3>Проверка Воли</h3><p>База ${i.skills['Воля']} ${p.skillMods?.['Воля']?`· модификатор сыщика ${p.skillMods['Воля']}`:''} · монстр ${esc(m.horror||'—')}.</p><div class="stat"><b>${Math.max(1,will+parseModifier(m.horror))}</b>кубиков до бонусов реакций</div></div><div class="step"><h3>Реакции и перебросы</h3><p>${esc(reactionHints(p,'Воля'))}</p></div><div class="step"><h3>Проверка Силы</h3><p>База ${i.skills['Сила']} ${p.skillMods?.['Сила']?`· модификатор сыщика ${p.skillMods['Сила']}`:''} · монстр ${esc(m.combat||'—')}.</p><div class="stat"><b>${Math.max(1,strength+parseModifier(m.combat))}</b>кубиков до бонусов имущества</div></div></div><div class="grid two" style="margin-top:12px"><div class="field"><label>Успехи Воли</label><input id="will-ok" type="number" min="0" value="0"></div><div class="field"><label>Успехи Силы</label><input id="str-ok" type="number" min="0" value="0"></div></div><button class="primary" style="width:100%;margin-top:12px" onclick="App.resolveCombat('${id}')">Применить результат раунда</button>`})}
function parseModifier(s){const m=String(s||'').match(/[−-](\d+)/);return m?-Number(m[1]):0}
function reactionHints(p,skill){const ids=[...(p.spells||[]),...(p.assets||[]),...(p.unique||[])],pool=[...(C.spells||[]),...(C.assets||[]),...(C.unique||[])],hits=ids.map(id=>pool.find(x=>x.id===id)).filter(x=>x&&(String(x.timing||'')+String(x.text||'')).match(/реакц|переброс|боев/iu));return hits.length?hits.map(x=>`${x.name}: ${x.text}`).join(' · '):`Подходящих реакций в цифровом инвентаре не найдено. Бросьте физические кубики для проверки ${skill}.`}
function resolveCombat(id){snapshot();const x=state.world.monsters.find(x=>x.id===id),m=[...(C.monsters||[]),...(C.epic||[])].find(a=>a.id===x.catalogId),p=player(),w=Number($('#will-ok').value)||0,s=Number($('#str-ok').value)||0,horror=Number((String(m.horror).split('/')[1]||0).match(/\d+/)?.[0]||0),damage=Number((String(m.combat).split('/')[1]||0).match(/\d+/)?.[0]||0);p.san=Math.max(0,p.san-Math.max(0,horror-w));p.hp=Math.max(0,p.hp-Math.max(0,damage-s));x.hp-=s;if(state.campaign.currentBoss?.id===id)state.campaign.currentBoss.hp=x.hp;p.stats.damage=(p.stats.damage||0)+s;if(x.hp<=0){state.world.monsters=state.world.monsters.filter(a=>a.id!==id);p.stats.kills=(p.stats.kills||0)+1;log('story',`${p.name} выдержал взгляд ${m.name} и нанёс решающий удар. Когда тварь исчезла, в локации ещё долго пахло озоном и морской солью.`)}else log('story',`${p.name} пережил схватку с ${m.name}. Монстр отступил лишь на несколько шагов — у него осталось ${x.hp} здоровья.`);if(p.hp===0||p.san===0)p.eliminated=true;closeModal();commit('Результат боя')}
function contactResult(){modal({title:'Результат контакта',body:`<div class="field"><label>Локация</label><select id="contact-loc">${LOCATIONS.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Что произошло?</label><textarea id="contact-story" placeholder="Коротко запишите результат физической карты"></textarea></div><div class="grid two"><div class="field"><label>HP (+ или −)</label><input id="contact-hp" type="number" value="0"></div><div class="field"><label>SAN (+ или −)</label><input id="contact-san" type="number" value="0"></div><div class="field"><label>Улики (+ или −)</label><input id="contact-clue" type="number" value="0"></div><div class="field"><label>Жетоны Древних на поле</label><input id="contact-eldritch" type="number" value="0"></div></div><button class="primary" style="width:100%;margin-top:12px" onclick="App.saveContact()">Применить всё</button>`})}
function saveContact(){const p=player(),i=myInv(),loc=$('#contact-loc').value,story=$('#contact-story').value||'Контакт оставил после себя больше вопросов, чем ответов.',h=Number($('#contact-hp').value)||0,s=Number($('#contact-san').value)||0,c=Number($('#contact-clue').value)||0,e=Number($('#contact-eldritch').value)||0;p.hp=Math.max(0,Math.min(i.hp,p.hp+h));p.san=Math.max(0,Math.min(i.san,p.san+s));p.clues=Math.max(0,p.clues+c);if(e)state.world.processes.push({id:uid(),kind:'Жетоны Древних',title:loc,text:'Размещены в результате контакта',tokens:e});p.stats.cities=(p.stats.cities||0)+1;log('story',`${p.name} исследовал ${loc}. ${story}`,`HP ${h}; SAN ${s}; улики ${c}; жетоны Древних ${e}`);closeModal();commit('Результат контакта')}
function clueContact(){modal({title:'Контакт с уликой',body:`<div class="field"><label>Локация улики</label><select id="clue-loc">${LOCATIONS.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="grid two"><button class="primary" onclick="App.resolveClue(true)">Улика получена</button><button onclick="App.resolveClue(false)">Контакт провален</button></div>`})}
function resolveClue(ok){const p=player(),loc=$('#clue-loc').value;if(ok){p.clues++;p.stats.clues=(p.stats.clues||0)+1;state.campaign.clues++;const idx=state.world.clues.findIndex(x=>x.location===loc);if(idx>=0)state.world.clues.splice(idx,1);log('story',`${p.name} нашёл в ${loc} зацепку, которую другие приняли бы за бессвязный бред.`)}else log('story',`${p.name} покинул ${loc}, так и не сумев отделить правду от наваждения.`);closeModal();commit()}
function trade(){const others=Object.values(state.players).filter(x=>x.id!==player()?.id);modal({title:'Обмен — отдельное действие',body:`<div class="field"><label>Общая локация</label><select id="trade-loc">${LOCATIONS.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Другой сыщик</label><select id="trade-player">${others.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div><p class="notice">Подтвердите, что оба сыщика физически находятся здесь. Передачу конкретных карт отметьте в их инвентаре.</p><button class="primary" onclick="App.confirmTrade()">Подтвердить обмен</button>`})}
function confirmTrade(){log('story',`${player().name} и ${state.players[$('#trade-player').value]?.name} обменялись имуществом в ${$('#trade-loc').value}.`);closeModal();commit()}
function drawMyth(){snapshot();state.campaign.mythIndex=(state.campaign.mythIndex+1)%state.campaign.mythDeck.length;state.campaign.mythStep=0;state.campaign.mythApplied=[];const card=MYTH.find(x=>x.id===state.campaign.mythDeck[state.campaign.mythIndex]);log('story',`Карта Мифа: «${card.title}». ${card.story}`);commit('Вытянута карта Мифа')}
function applyMythStep(){const card=MYTH.find(x=>x.id===state.campaign.mythDeck[state.campaign.mythIndex]),steps=mythSteps(card),idx=state.campaign.mythStep,step=steps[idx];if(state.campaign.mythApplied.includes(`${card.id}:${idx}`))return toast('Этот шаг уже выполнен');if(step.type==='clue')return mythClueInput(card,idx);if(step.type==='gate')return mythGateInput(card,idx);if(step.type==='monster')return mythMonsterInput(card,idx);applyKnownMyth(step,card);finishStep(card,idx,step)}
function finishStep(card,idx,step){state.campaign.mythApplied.push(`${card.id}:${idx}`);state.campaign.mythStep++;log('story',step.type?`${step.title}. ${step.story}`:`Вступление «${card.title}» прочитано.`);closeModal();commit(`Миф: ${step.title}`)}
function applyKnownMyth(step,card){if(step.type==='omen'){const order=['зелёное','синее','красное'],next=(order.indexOf(state.world.omen)+1)%3;state.world.omen=order[next];const same=state.world.gates.filter(g=>g.symbol===state.world.omen).length;state.world.doom=Math.max(0,state.world.doom-same)}if(step.type==='surge'){const gates=state.world.gates;if(gates.length)toast(`Наплыв: добавьте ${Math.max(1,Object.keys(state.players).length)} монстров к вратам с совпавшим знамением`)}if(step.type==='effect'&&(card.category||'').toLowerCase().includes('слух'))state.world.rumors.push({id:uid(),kind:'Слух',title:card.title,text:card.effect,tokens:Number(String(card.tokens).match(/\d+/)?.[0]||0)})}
function mythClueInput(card,idx){modal({title:'Где появились улики?',body:`<p>Заполните столько полей, сколько требует число сыщиков и карта.</p>${[1,2,3,4,5].map(n=>`<div class="field"><label>Улика ${n}</label><select class="myth-clue"><option value="">Не вытягивали</option>${LOCATIONS.slice(0,16).map(x=>`<option>${x}</option>`).join('')}</select></div>`).join('')}<button class="primary" style="width:100%;margin-top:12px" onclick="App.saveMythClues('${card.id}',${idx})">Запомнить и продолжить</button>`})}
function saveMythClues(cardId,idx){const locs=[...document.querySelectorAll('.myth-clue')].map(x=>x.value).filter(Boolean);locs.forEach(location=>state.world.clues.push({id:uid(),location}));const seen=locs.map((x,n)=>`${x}: ${['ночной сторож видел свет под мостовой','ребёнок нарисовал существо, которого никто ему не описывал','из закрытого дома всю ночь слышали стук','компас экспедиции указывал прямо в землю','морская вода выступила на стенах вдали от берега'][n]}`).join('. ');log('story',seen||'На этот раз ни одно свидетельство не удалось привязать к месту.');finishStep(MYTH.find(x=>x.id===cardId),idx,mythSteps(MYTH.find(x=>x.id===cardId))[idx])}
function mythGateInput(card,idx){modal({title:'Открытие врат',body:`<div class="field"><label>Локация жетона врат</label><select id="myth-gate-loc">${LOCATIONS.slice(0,16).map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Символ врат</label><select id="myth-gate-symbol"><option>зелёное</option><option>синее</option><option>красное</option></select></div><div class="field"><label>Монстр, вышедший из врат</label><select id="myth-gate-monster"><option value="">Добавить позже</option>${(C.monsters||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div><button class="primary" onclick="App.saveMythGate('${card.id}',${idx})">Открыть врата</button>`})}
function saveMythGate(cardId,idx){const location=$('#myth-gate-loc').value,symbol=$('#myth-gate-symbol').value,mid=$('#myth-gate-monster').value;state.world.gates.push({id:uid(),location,symbol});if(mid)addMonsterObject(mid,location);log('story',`В ${location} воздух раскололся, открыв врата под знаком «${symbol}».${mid?' Из разлома вышло чудовище.':''}`);finishStep(MYTH.find(x=>x.id===cardId),idx,mythSteps(MYTH.find(x=>x.id===cardId))[idx])}
function mythMonsterInput(card,idx){modal({title:'Появление монстра',body:`<div class="field"><label>Монстр</label><select id="myth-monster">${(C.monsters||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Локация</label><select id="myth-monster-loc">${LOCATIONS.map(x=>`<option>${x}</option>`).join('')}</select></div><button class="primary" onclick="App.saveMythMonster('${card.id}',${idx})">Добавить</button>`})}
function saveMythMonster(cardId,idx){const mid=$('#myth-monster').value,loc=$('#myth-monster-loc').value;addMonsterObject(mid,loc);finishStep(MYTH.find(x=>x.id===cardId),idx,mythSteps(MYTH.find(x=>x.id===cardId))[idx])}
function finishMyth(){state.campaign.mythIndex=-1;state.campaign.mythStep=0;state.meta.phase='Действия';state.meta.round++;log('story',`Бедствие отступает. Мир входит в ${state.meta.round}-й раунд, изменившийся, но ещё не сломленный.`);commit()}
function addGate(){simpleLocation('Добавить врата',(location)=>{state.world.gates.push({id:uid(),location,symbol:state.world.omen});log('technical',`Добавлены врата: ${location}`);commit()})}function addFieldClue(){simpleLocation('Добавить улику',(location)=>{state.world.clues.push({id:uid(),location});log('technical',`Добавлена улика: ${location}`);commit()})}
function simpleLocation(title,fn){window._locationCallback=fn;modal({title,body:`<div class="field"><select id="simple-loc">${LOCATIONS.map(x=>`<option>${x}</option>`).join('')}</select></div><button class="primary" onclick="App.finishLocation()">Добавить</button>`})}function finishLocation(){window._locationCallback?.($('#simple-loc').value);window._locationCallback=null;closeModal()}
function removeWorld(id){state.world.gates=state.world.gates.filter(x=>x.id!==id);state.world.clues=state.world.clues.filter(x=>x.id!==id);commit()}
function addMonster(){modal({title:'Добавить монстра',body:`<div class="field"><label>Название</label><input id="monster-search" placeholder="Поиск" oninput="App.filterMonsters()"></div><div id="monster-list" class="stack" style="margin-top:10px">${[...(C.monsters||[]),...(C.epic||[])].map(x=>`<button data-monster-search="${esc(x.name.toLowerCase())}" onclick="App.pickMonster('${x.id}')">${esc(x.name)} · ${x.hp} HP</button>`).join('')}</div>`})}function filterMonsters(){const q=$('#monster-search').value.toLowerCase();document.querySelectorAll('[data-monster-search]').forEach(x=>x.hidden=!x.dataset.monsterSearch.includes(q))}function pickMonster(id){window._monsterPick=id;simpleLocation('Где появился монстр?',loc=>{addMonsterObject(id,loc);commit()})}
function addMonsterObject(id,location){const m=[...(C.monsters||[]),...(C.epic||[])].find(x=>x.id===id);state.world.monsters.push({id:uid(),catalogId:id,name:m?.name||id,location,hp:m?.hp||1,maxHp:m?.hp||1,boss:!!m?.epic})}
function hurtMonster(id){const x=state.world.monsters.find(x=>x.id===id);if(!x)return;x.hp--;if(state.campaign.currentBoss?.id===id)state.campaign.currentBoss.hp=x.hp;if(x.hp<=0){state.world.monsters=state.world.monsters.filter(a=>a.id!==id);log('story',`${x.name} повержен.`)}commit()}
function resolveProcess(id){const x=[...state.world.rumors,...state.world.processes].find(x=>x.id===id);modal({title:x.title,body:`<p>Как завершился этот процесс?</p><div class="grid two"><button class="primary" onclick="App.finishProcess('${id}','победа')">Победа</button><button class="danger" onclick="App.finishProcess('${id}','провал')">Провал</button><button onclick="App.finishProcess('${id}','исправление')">Исправление ведущего</button></div>`})}function finishProcess(id,outcome){state.world.rumors=state.world.rumors.filter(x=>x.id!==id);state.world.processes=state.world.processes.filter(x=>x.id!==id);log('story',`Активный процесс завершён: ${outcome}.`);closeModal();commit()}
function bumpCampaign(k){if(!leads()&&k!=='clues')return toast('Общее состояние подтверждает ведущий');state.campaign[k]++;checkChapter();commit()}
function addCity(){modal({title:'Исследованный особый город',body:`<div class="field"><select id="city-pick">${SPECIAL.filter(x=>!state.campaign.cities.includes(x)).map(x=>`<option>${x}</option>`).join('')}</select></div><button class="primary" onclick="App.saveCity()">Отметить контакт</button>`})}function saveCity(){const city=$('#city-pick').value;if(!city)return;state.campaign.cities.push(city);const p=player();if(p)p.stats.cities=(p.stats.cities||0)+1;log('story',`${p?.name||'Экспедиция'} добрался до ${city} и нашёл там часть ответа.`);closeModal();checkChapter();commit()}
function checkChapter(){const ch=CHAPTERS[state.campaign.chapter];if(!ch||state.campaign.currentBoss)return;if(state.campaign.clues>=ch.need.clues&&state.campaign.gates>=ch.need.gates&&state.campaign.cities.length>=ch.need.cities){state.campaign.stage='preparation';log('story','Все части расследования сошлись. До встречи с тем, что стояло за событиями главы, остаётся одна фаза подготовки.')}}
function revealBoss(){const chapter=state.campaign.chapter,used=state.campaign.bosses;if(state.campaign.stage!=='preparation')return;const pool=chapter===2?(C.epic||[]).filter(x=>/ктул/i.test(x.name)):(C.epic||[]).filter(x=>!used.includes(x.id)&&!/ктул/i.test(x.name));const b=pool[Math.floor(Math.random()*pool.length)]||C.epic?.[0],city=state.campaign.cities[1]||state.campaign.cities[0]||SPECIAL[Math.floor(Math.random()*SPECIAL.length)];state.campaign.currentBoss={id:uid(),catalogId:b.id,name:b.name,hp:b.hp||8,maxHp:b.hp||8,location:city};state.campaign.stage='boss';state.campaign.bosses.push(b.id);state.world.monsters.push({...state.campaign.currentBoss,boss:true});log('story',`В ${city} улицы опустели раньше заката. Из тумана вышел ${b.name} — истинный хозяин бедствий этой главы.`);commit()}
function completeBoss(){const b=state.campaign.currentBoss;if(!b)return;state.world.monsters=state.world.monsters.filter(x=>x.catalogId!==b.catalogId);log('story',`${CHAPTERS[state.campaign.chapter].end} ${Object.values(state.players).map(p=>p.name).join(', ')} останутся свидетелями этой победы.`);state.campaign.currentBoss=null;state.campaign.chapter++;state.campaign.clues=0;state.campaign.gates=0;state.campaign.cities=[];state.campaign.stage='checklist';state.campaign.storyOpen=true;if(state.campaign.chapter>=3)state.meta.status='finished';commit()}
function addMemory(){if(!leads())return toast('Памятный момент добавляет ведущий');modal({title:'Памятный момент',body:`<div class="field"><textarea id="memory" placeholder="Что экспедиция не должна забыть?"></textarea></div><button class="primary" onclick="App.saveMemory()">Добавить в хронику</button>`})}function saveMemory(){const t=$('#memory').value.trim();if(t)log('story',t);closeModal();commit()}
function chronicleModal(){modal({title:'Летопись экспедиции',body:chronicle(true)})}
function assignCohost(){const ps=Object.values(state.players).filter(x=>x.ownerUid!==state.meta.hostUid);modal({title:'Назначить соведущего',body:ps.map(p=>`<button style="width:100%;margin-bottom:8px" onclick="App.setCohost('${p.ownerUid}')">${esc(p.name)}</button>`).join('')||'<p>Других игроков пока нет.</p>'})}function setCohost(id){state.meta.cohostUid=id;closeModal();commit()}
function transferHost(){const ps=Object.values(state.players).filter(x=>x.ownerUid!==state.meta.hostUid);modal({title:'Передать роль ведущего',body:ps.map(p=>`<button style="width:100%;margin-bottom:8px" onclick="App.setHost('${p.ownerUid}')">${esc(p.name)}</button>`).join('')||'<p>Других игроков пока нет.</p>'})}function setHost(id){state.meta.hostUid=id;state.meta.cohostUid='';closeModal();commit()}
function undo(){const s=state.undo.shift();if(!s)return toast('Нет операции для отмены');state.world=s.world;state.campaign=s.campaign;state.players=s.players;log('technical','Ведущий отменил последнюю общую операцию');commit()}
function resetDialog(){modal({title:'Сбросить общую партию',body:`<p>Введите код <b>${roomCode||'СБРОС'}</b>. Хроника будет удалена без возможности восстановления.</p><div class="field"><input id="reset-code"></div><button class="danger" onclick="App.resetGame()">Сбросить партию</button>`})}async function resetGame(){if($('#reset-code').value.trim().toUpperCase()!==(roomCode||'СБРОС'))return toast('Код не совпадает');if(roomCode){await RoomAPI.remove(roomCode);RoomAPI.stop();localStorage.removeItem('eh-v05-room');roomCode=''}state=fresh();state.meta.hostUid=me.uid;closeModal();screen='entry';saveLocal();render()}
window.App={solo,roomDialog,createRoom,joinRoom,leave,toggleMenu,go,closeModal,cthulhu,collapseStory,choose,toggleReady,setPhase,nextRound,counter,changeCounter,tickets,ticket,skill,rest,applyRest,addInventory,pickInventory,filterCatalog,takeItem,startCombat,chooseCombatMonsters,combatWizard,resolveCombat,contactResult,saveContact,clueContact,resolveClue,trade,confirmTrade,drawMyth,applyMythStep,saveMythClues,saveMythGate,saveMythMonster,finishMyth,addGate,addFieldClue,finishLocation,removeWorld,addMonster,filterMonsters,pickMonster,hurtMonster,resolveProcess,finishProcess,bumpCampaign,addCity,saveCity,revealBoss,completeBoss,addMemory,saveMemory,chronicle:chronicleModal,assignCohost,setCohost,transferHost,setHost,undo,resetDialog,resetGame};
boot();
})();
