/* Streamlined v0.4 — narrative campaign, city route, bosses and personal epilogues. */
const STORY_CITY_GROUPS={
 america:['Сан-Франциско','Аркхэм','Буэнос-Айрес'],
 europe:['Лондон','Рим','Стамбул'],
 asia:['Шанхай','Токио','Сидней']
};
const STORY_CITY={
 'Сан-Франциско':{flavor:'В портовых архивах сохранились показания моряков, видевших башни там, где ещё вчера было открытое море.',rewards:['Улучшить Внимание','Получить 1 улику']},
 'Аркхэм':{flavor:'В закрытом фонде Мискатоникского университета обнаруживается книга, страницы которой становятся влажными с наступлением темноты.',rewards:['Изучить случайное заклинание','Улучшить Знание']},
 'Буэнос-Айрес':{flavor:'На ночном рынке торговец узнаёт знак Р’льеха и молча открывает ящик с вещами пропавшей экспедиции.',rewards:['Получить случайную безделушку или союзника','Получить 1 улику']},
 'Лондон':{flavor:'Письма из разных стран сходятся в одном почтовом отделении. Все отправители исчезли в одну и ту же ночь.',rewards:['Получить 2 улики','Восстановить 2 рассудка']},
 'Рим':{flavor:'Под старой часовней сыщики находят мозаику, на которой святые удерживают щупальца под толщей воды.',rewards:['Получить Благословение','Восстановить 1 здоровье и 1 рассудок']},
 'Стамбул':{flavor:'Посредник на базаре знает имена культистов, но называет цену лишь после того, как за вами закрываются двери.',rewards:['Получить случайного союзника','Улучшить Общение']},
 'Шанхай':{flavor:'В книге портовых сборов обнаруживается корабль, заходивший в гавань задолго до основания города.',rewards:['Получить случайную книгу','Улучшить Знание']},
 'Токио':{flavor:'Инженер утверждает, что записал голос со дна океана. На плёнке голос произносит имена сыщиков.',rewards:['Полностью снять задержку и восстановить силы','Улучшить Внимание']},
 'Сидней':{flavor:'Из разбитой лодки извлекают оружие, покрытое солью и чёрной кровью, которая никак не засыхает.',rewards:['Получить случайное оружие','Улучшить Силу']}
};
const STORY_CHAPTERS=[
 {title:'Сны о затонувшем городе',boss:'Ктилла',clues:2,gates:0,monsters:2,intro:'Сначала это были только сны. Незнакомые друг другу люди просыпались с солёной водой на губах и чертили один и тот же город: чёрные башни под тяжёлым зелёным небом. Затем в гавани нашли тело человека, который утонул за тысячи километров от моря. Среди его вещей лежала карта с двумя обведёнными городами.',bossIntro:'Собранные свидетельства складываются в имя, которое никто не решается произнести вслух. Вода у берегов темнеет, и из глубины поднимается Ктилла — первая, кто ответил на зов спящего города.',outro:'Когда Ктилла уходит под воду, море ещё долго выбрасывает на берег обломки чужой архитектуры. На одном из камней вырезан знак человеческой рукой. Значит, Ктулху зовёт не только чудовищ: кто-то среди людей уже готовит ему путь.'},
 {title:'Культ среди людей',boss:'Звёздное отродье',clues:4,gates:1,monsters:4,intro:'Следы из первой главы ведут не к древнему храму, а к людям. Банкиры, врачи, портовые рабочие и чиновники годами передавали друг другу части одного ритуала, не зная полной картины. Теперь курьеры культа направляются в два города, и времени на ошибку больше нет.',bossIntro:'За человеческими голосами скрывался настоящий распорядитель ритуала. Над крышами расправляет крылья Звёздное отродье, а культисты приветствуют его так, словно ждали всю жизнь.',outro:'Тело отродья рассыпается в вязкий пепел, но среди останков находится астрономическая таблица. Все расчёты сходятся на одной ночи. Звёзды почти заняли свои места, и следующая волна принесёт уже не слугу.'},
 {title:'Звёзды заняли свои места',boss:'Ктулху',clues:5,gates:3,monsters:6,intro:'Небо меняется незаметно: знакомые созвездия оказываются на полпальца ближе друг к другу. По всему миру часы начинают отставать на одинаковое число секунд. Р’льех больше не снится — его мокрые улицы проступают поверх настоящих городов, и каждый открытый разлом приближает пробуждение.',bossIntro:'Океан отступает от берегов, обнажая лестницы невозможной длины. Р’льех поднимается, и вместе с ним восстаёт Ктулху. Теперь улики, закрытые врата и пережитые потери имеют смысл лишь в том случае, если сыщики сделают последний шаг.',outro:'Ктулху падает не как живое существо: сама реальность на мгновение забывает его форму. Башни Р’льеха уходят под воду, увлекая за собой чудовищ и голоса. Мир спасён — но никто из тех, кто стоял на берегу, уже не сможет назвать его прежним.'}
];
const STORY_HEROES={
 'Акачи Оньеле':{calling:'Акачи всегда знала, что врата помнят прикосновение тех, кто их закрывает.',victory:'Она вернулась к дорогам между мирами не как странница, а как их молчаливый страж.',scarred:'Раны зажили, но по ночам на её коже проступали очертания созвездий, которых нет на земном небе.',broken:'Часть её разума осталась за последними вратами; иногда Акачи отвечала на вопросы голосом человека, ещё не родившегося.',dark:'В последний миг голоса предложили ей не закрывать путь, а занять место по другую сторону. Никто не узнал, какой ответ она дала.',dead:'Последние врата закрылись вслед за Акачи. На земле не осталось могилы — только тропа, которую больше никто не решался пройти.'},
 'Джим Калвер':{calling:'Джим слышал ритм надвигающегося конца раньше, чем остальные замечали первые знаки.',victory:'Его новая мелодия возвращала сон тем, кого ещё мучил зов Р’льеха.',scarred:'Он продолжал играть, хотя некоторые ноты заставляли старые раны снова кровоточить.',broken:'После победы Джим слышал музыку даже в полной тишине и однажды ушёл за мелодией, которую никто другой не слышал.',dark:'В его последней записи появился второй музыкант. Знатоки клялись, что человеческие руки не способны сыграть эту партию.',dead:'На похоронах музыканты обнаружили в нотах незнакомый последний такт. Они сыграли его один раз — и море ответило.'},
 'Лили Чен':{calling:'Лили всю жизнь превращала страх в движение, а боль — в точность следующего удара.',victory:'Она покинула поле боя без торжества: победа означала лишь то, что завтра другим не придётся сражаться.',scarred:'Тело больше не слушалось её безупречно, но ученики запоминали каждое движение, которое она ещё могла показать.',broken:'Разум Лили продолжал вести бой после его окончания; в пустых комнатах она уклонялась от ударов невидимого противника.',dark:'Она поняла, что сила врага может стать оружием. С каждым годом её школа всё меньше напоминала человеческое искусство.',dead:'Лили осталась стоять между чудовищем и товарищами, когда отступать было уже поздно. Ни один удар после её падения не достиг остальных.'},
 'Жаклин Файн':{calling:'Жаклин видела возможные смерти товарищей задолго до того, как они сделали первый шаг.',victory:'Впервые будущее стало тихим. Она позволила себе прожить целое утро, не заглядывая в следующий час.',scarred:'Каждый шрам напоминал Жаклин о будущем, которое ей всё-таки удалось отменить.',broken:'Все спасённые варианты мира продолжали существовать в её голове одновременно, и врачи не понимали, с кем именно разговаривают.',dark:'Среди тысяч будущих Жаклин выбрала одно, в котором сама получила власть изменить остальные. Цена осталась её тайной.',dead:'Она знала минуту собственной смерти с самого начала и всё равно пришла. Последнее предсказание Жаклин спасло тех, кто стоял рядом.'},
 'Лола Хейз':{calling:'Лола привыкла носить чужие лица, но перед концом света ей пришлось решить, какое из них принадлежит ей самой.',victory:'Позже она сыграла эту историю на сцене. Публика назвала финал невозможным и не заметила, что актриса плачет по-настоящему.',scarred:'Грим скрывал шрамы от зрителей, но не от Лолы; каждое зеркало возвращало ей ночь последнего боя.',broken:'Она продолжала менять роли, пока однажды друзья не поняли, что настоящая Лола больше не выходит на поклон.',dark:'Предложение культа показалось ей последней великой ролью. Со временем никто уже не мог сказать, где закончилась игра.',dead:'Последними словами Лолы стала реплика из пьесы, которой никто не писал. Выжившие запомнили её как обещание вернуться.'},
 'Диана Стэнли':{calling:'Диана знала язык культа и слишком хорошо понимала, почему его обещания звучат убедительно.',victory:'Она уничтожила последние записи секты и посвятила остаток жизни поиску тех, кого ещё можно было вернуть.',scarred:'Каждая рана казалась справедливой платой за прежние грехи, хотя товарищи давно перестали считать её виновной.',broken:'После победы Диана добровольно заперла себя там, где стены были покрыты защитными знаками, и запретила открывать дверь.',dark:'Когда культ позвал её по старому имени, Диана ответила. Возможно, именно поэтому остальные получили шанс уйти.',dead:'Она умерла, произнося слова ритуала наоборот. Те, кто когда-то называл её предательницей, выжили благодаря этой последней измене культу.'},
 'Марк Харриган':{calling:'Для Марка чудовища были ещё одной войной — хуже прежней, но хотя бы здесь враг не скрывал лица.',victory:'Он не искал славы. Люди, которых Марк вывел из обречённых улиц, были единственной наградой, которую он признавал.',scarred:'Война закончилась, но тело продолжало вести её при каждом резком звуке и каждой бессонной ночи.',broken:'Марк просыпался с оружием в руках и докладывал о противнике, которого никто больше не видел.',dark:'Он согласился стать оружием, потому что оружие не обязано спрашивать, кто держит его за рукоять.',dead:'Марк удерживал проход до последнего патрона. Когда товарищи вернулись за ним, вокруг лежали только чудовища.'},
 'Норман Уизерс':{calling:'Норман всю жизнь смотрел на звёзды и слишком поздно понял, что некоторые из них смотрят в ответ.',victory:'Он исправил карты неба и спрятал доказательства там, где следующий внимательный астроном обязательно их найдёт.',scarred:'Телескоп приходилось настраивать дрожащими руками, но Норман продолжал каждую ночь проверять положение звёзд.',broken:'В лечебнице он рисовал одно созвездие снова и снова, утверждая, что оно приближается.',dark:'Норман сохранил одну страницу расчётов. Знание о следующем пробуждении оказалось слишком драгоценным, чтобы уничтожить его.',dead:'Последняя запись Нормана содержала координаты безопасного пути. Благодаря ей остальные увидели рассвет.'},
 'Сайлас Марш':{calling:'Сайлас доверял морю больше, чем людям, пока море не заговорило голосами его собственной крови.',victory:'Он снова вышел в плавание, но никогда больше не пересекал место, где под водой лежали чёрные башни.',scarred:'Соль разъедала незажившие раны, и всё же только на палубе Сайлас чувствовал себя живым.',broken:'Его нашли в лодке без вёсел. Сайлас утверждал, что ждал прилива, который унесёт его домой.',dark:'Когда глубина назвала его своим, он не стал спорить. На берег вернулось нечто, сохранившее его лицо и память.',dead:'Море забрало Сайласа, но вынесло остальных к берегу. Старые моряки говорили, что это был честный обмен.'},
 'Лео Андерсон':{calling:'Лео терял экспедиции и раньше, поэтому считал каждого вернувшегося личной победой.',victory:'В официальном отчёте он приписал успех команде и вычеркнул всё, во что миру было опасно поверить.',scarred:'Лео хромал, но продолжал собирать экспедиции — теперь он лучше других знал цену плохой подготовки.',broken:'Он каждый вечер пересчитывал участников давно завершившегося похода и всегда находил одного лишнего.',dark:'Лео вывел команду из ловушки по дороге, показанной врагом. Лишь позже он понял, куда должна привести следующая экспедиция.',dead:'Он ушёл последним, как и обещал. В журнале экспедиции напротив имени Лео осталось одно слово: «руководитель».'},
 'Чарли Кейн':{calling:'Чарли знал, что миром управляют договорённости, но некоторые подписи ставятся кровью.',victory:'Он убедил правительства восстановить разрушенные города, оставив настоящую причину катастрофы за закрытыми дверями.',scarred:'Публичные выступления давались тяжело, однако Чарли научился улыбаться прежде, чем боль успевала отразиться на лице.',broken:'Он видел заговор в каждом совещании и в конце концов перестал различать культ и собственных союзников.',dark:'Чарли сохранил связи культа и превратил их в новую систему влияния. Она работала пугающе хорошо.',dead:'После смерти Чарли десятки людей получили письма с инструкциями. Его последний план продолжал спасать мир без него.'},
 'Триш Скарборо':{calling:'Триш привыкла искать правду в чужой лжи и замечать то, что профессиональные мистики принимали за судьбу.',victory:'Она закрыла дело, но оставила одну копию отчёта в архиве под именем, которого не существовало.',scarred:'Триш научилась использовать боль как сигнал опасности; старые раны предупреждали её раньше любых разведданных.',broken:'После операции она продолжала получать сообщения от уничтоженной сети и отвечала на каждое.',dark:'Последний шифр предлагал ей место внутри новой организации. Триш вошла туда как двойной агент — или хотела так думать.',dead:'Её сообщение оборвалось на полуслове, но переданные координаты позволили остальным нанести последний удар.'}
};

function storyShuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function storyRoute(){const a=storyShuffle(STORY_CITY_GROUPS.america),e=storyShuffle(STORY_CITY_GROUPS.europe),s=storyShuffle(STORY_CITY_GROUPS.asia);return[[a[0],e[0]],[e[1],s[0]],[s[1],a[1]]].map(storyShuffle)}
function storyStats(){return{clues:0,clueContacts:0,cities:[],gates:0,damage:0,kills:0,bossDamage:0,bossKills:0,hpLost:0,sanLost:0,successes:0,upgrades:0}}
function ensureStory(){
 state.storyCampaign=state.storyCampaign||{version:1,route:storyRoute(),chapter:Math.max(1,state.campaign?.chapter||1),chapters:[{},{},{}],cityRewards:{},finished:false,result:'',epilogue:''};
 state.storyCampaign.route=state.storyCampaign.route?.length===3?state.storyCampaign.route:storyRoute();state.storyCampaign.chapters=state.storyCampaign.chapters||[{},{},{}];state.storyCampaign.cityRewards=state.storyCampaign.cityRewards||{};
 state.investigators.forEach(x=>x.storyStats={...storyStats(),...(x.storyStats||{})});
 const ch=state.storyCampaign.chapter||1,boss=state.monsters.find(m=>m.storyBossChapter===ch);
 if(boss&&boss.hp===0&&!state.storyCampaign.chapters[ch-1].bossDefeated){state.storyCampaign.chapters[ch-1].bossDefeated=true;logEvent(`${boss.name} повержен. Развязка главы готова.`)}
 state.campaign.chapter=Math.min(3,state.storyCampaign.chapter||1);state.campaign.won=state.storyCampaign.finished&&state.storyCampaign.result==='victory';
}
ensureStory();

function storyRequirements(n){const c=STORY_CHAPTERS[n-1],cities=state.storyCampaign.route[n-1];return[['clues',c.clues,`Провести ${c.clues} поисковых контакта`],...cities.map(city=>[`city:${city}`,1,`Исследовать ${city}`]),['gates',c.gates,`Закрыть ${c.gates} врат`],['monsters',c.monsters,`Победить ${c.monsters} монстров`]].filter(r=>r[1]>0)}
function storyChecklistMet(n){return storyRequirements(n).every(([key,target])=>campaignValue(key)>=target)}
chapterComplete=function(ch){const n=ch.number||1;return Boolean(state.storyCampaign?.chapters?.[n-1]?.bossDefeated)};
updateCampaign=function(){ensureStory();renderCampaign()};
cityOptions=function(selected=''){return `<option value="">Не относится к именному городу</option>${Object.keys(STORY_CITY).map(c=>`<option ${c===selected?'selected':''}>${c}</option>`).join('')}`};

function storyProgress(key,target,label){const value=campaignValue(key),done=value>=target,shown=key.startsWith('city:')?(done?1:0):Math.min(value,target);return `<li class="${done?'done':''}"><span class="mission-check">${done?'✓':'○'}</span><div><b>${esc(label)}</b><small>${key.startsWith('city:')?(done?'Контакт записан':'Ещё не исследовано'):`${shown} / ${target}`}</small></div></li>`}
function renderCampaign(){
 const root=document.querySelector('#campaign-progress');if(!root)return;ensureStory();const sc=state.storyCampaign;
 if(sc.finished){root.innerHTML=sc.epilogue||storyBuildEpilogue(sc.result==='victory');return}
 const n=sc.chapter,c=STORY_CHAPTERS[n-1],cs=sc.chapters[n-1],route=sc.route[n-1];
 if(!cs.introSeen){root.innerHTML=`<div class="story-prologue"><span>ГЛАВА ${n} ИЗ 3</span><h3>${esc(c.title)}</h3><p>${esc(c.intro)}</p><div class="story-route">${route.map(x=>`<span>${esc(x)}</span>`).join('')}</div><button class="primary wide" onclick="beginStoryChapter(${n})">Начать расследование</button></div>`;return}
 if(cs.bossDefeated){root.innerHTML=`<div class="story-outro"><span>РАЗВЯЗКА ГЛАВЫ ${n}</span><h3>${esc(c.title)}</h3><p>${esc(c.outro)}</p><button class="primary wide" onclick="finishStoryChapter(${n})">${n<3?'Перейти к следующей главе':'Узнать судьбу сыщиков'}</button></div>${campaignTotals()}`;return}
 const ready=storyChecklistMet(n),boss=state.monsters.find(m=>m.storyBossChapter===n&&m.hp>0);
 root.innerHTML=`<div class="chapter-tabs">${STORY_CHAPTERS.map((x,i)=>`<button class="${i+1===n?'active':''} ${sc.chapters[i]?.bossDefeated?'complete':''}" onclick="previewChapter(${i+1})"><span>Глава ${i+1}</span><b>${esc(x.title)}</b></button>`).join('')}</div><div class="chapter-current"><div class="chapter-story"><span>АКТИВНАЯ ГЛАВА · МАРШРУТ ${route.map(esc).join(' → ')}</span><h3>${esc(c.title)}</h3><p class="story-copy">${esc(c.intro)}</p><p class="chapter-reward">Контакт в каждом именном городе впервые даёт этому сыщику особую подготовку.</p></div><ol class="mission-list">${storyRequirements(n).map(r=>storyProgress(...r)).join('')}</ol></div>${campaignTotals()}<div class="boss-panel"><span>${boss?'БОСС НА ПОЛЕ':ready?'ЧЕК-ЛИСТ ЗАВЕРШЁН':'КУЛЬМИНАЦИЯ ЗАКРЫТА'}</span><h4>${esc(c.boss)}</h4><p>${boss?`Бой идёт в ${esc(boss.location)}. Нанесённый урон сохраняется между контактами.`:ready?esc(c.bossIntro):'Сначала соберите свидетельства, подготовьтесь в городах и выполните задачи главы.'}</p>${ready&&!boss?`<button class="primary" onclick="startStoryBoss(${n})">Начать финал главы</button>`:''}</div>${state.doom<=0?'<button class="danger campaign-danger" onclick="finishStoryCampaign(false)">Мир погиб · написать эпилог</button>':''}`;
}
window.beginStoryChapter=n=>{state.storyCampaign.chapters[n-1].introSeen=true;logEvent(`Началась глава ${n}: «${STORY_CHAPTERS[n-1].title}». Маршрут: ${state.storyCampaign.route[n-1].join(' и ')}.`);render()};
window.previewChapter=n=>{const c=STORY_CHAPTERS[n-1],route=state.storyCampaign.route[n-1];modal(`<h2>Глава ${n} · ${esc(c.title)}</h2><p class="mythos-prose">${esc(c.intro)}</p><div class="story-route">${route.map(x=>`<span>${esc(x)}</span>`).join('')}</div><ol class="mission-list preview">${storyRequirements(n).map(r=>storyProgress(...r)).join('')}</ol><p class="note">Сюжетная кампания — хоумрул Streamlined. Физические контакты и проверки сохраняются.</p>`)};
window.startStoryBoss=n=>{if(!storyChecklistMet(n))return;const c=STORY_CHAPTERS[n-1],location=state.storyCampaign.route[n-1][1];let source=[...catalog.epic,...catalog.monsters].find(m=>m.name===c.boss);if(!source&&c.boss==='Звёздное отродье')source=catalog.monsters.find(m=>/Зв[её]здное отродье/i.test(m.name));if(!source)return alert(`В каталоге не найден монстр «${c.boss}».`);addMonsterToState(source,location);const m=state.monsters[state.monsters.length-1],hp=n===2?state.investigators.length+3:monsterMaxHp(source);m.hp=m.hpMax=Math.max(3,hp);m.storyBossChapter=n;m.location=location;state.storyCampaign.chapters[n-1].bossStarted=true;logEvent(`${c.boss} появляется в ${location}. Начинается кульминация главы ${n}.`);render()};
window.finishStoryChapter=n=>{if(!state.storyCampaign.chapters[n-1].bossDefeated)return;if(n<3){state.storyCampaign.chapter=n+1;state.campaign.chapter=n+1;logEvent(`Глава ${n} завершена. Начинается «${STORY_CHAPTERS[n].title}».`);render()}else finishStoryCampaign(true)};

function storyItem(filter){const list=[...(catalog.assets||[]),...(catalog.unique||[])].filter(filter);return list[Math.floor(Math.random()*list.length)]}
function storySpell(){const list=catalog.spells||[];return list[Math.floor(Math.random()*list.length)]}
function addStoryItem(x,item){if(item&&!x.items.includes(item.name)){x.items.push(item.name);return item.name}return ''}
window.applyStoryReward=(i,city,choice)=>{const x=state.investigators[i],key=`${x.name}:${city}`;if(state.storyCampaign.cityRewards[key])return;let result='';const skill=k=>{x.skills[k]++;x.storyStats.upgrades++;result=`${k} повышен до ${x.skills[k]}`};
 if(city==='Сан-Франциско')choice? (x.clues++,x.storyStats.clues++,result='получена 1 улика'):skill('Внимание');
 if(city==='Аркхэм')choice?skill('Знание'):result=`изучено заклинание «${addStoryItem(x,storySpell())}»`;
 if(city==='Буэнос-Айрес')choice?(x.clues++,x.storyStats.clues++,result='получена 1 улика'):result=`получено имущество «${addStoryItem(x,storyItem(a=>/безделуш|союзник/i.test(a.type||'')))}»`;
 if(city==='Лондон')choice?(x.san=Math.min(x.sanMax,x.san+2),result='восстановлено 2 рассудка'):(x.clues+=2,x.storyStats.clues+=2,result='получены 2 улики');
 if(city==='Рим')choice?(x.hp=Math.min(x.hpMax,x.hp+1),x.san=Math.min(x.sanMax,x.san+1),result='восстановлены здоровье и рассудок'):(x.conditions.push({type:'blessed'}),result='получено Благословение');
 if(city==='Стамбул')choice?skill('Общение'):result=`получен союзник «${addStoryItem(x,storyItem(a=>/союзник/i.test(a.type||'')))}»`;
 if(city==='Шанхай')choice?skill('Знание'):result=`получена книга «${addStoryItem(x,storyItem(a=>/книга/i.test(a.type||'')))}»`;
 if(city==='Токио')choice?skill('Внимание'):(x.delayed=false,x.hp=Math.min(x.hpMax,x.hp+1),x.san=Math.min(x.sanMax,x.san+1),result='снята задержка и восстановлены силы');
 if(city==='Сидней')choice?skill('Сила'):result=`получено оружие «${addStoryItem(x,storyItem(a=>/оружие/i.test(a.type||'')))}»`;
 state.storyCampaign.cityRewards[key]=true;logEvent(`${x.name} завершает подготовку в городе ${city}: ${result}.`);document.querySelector('#modal').close();render()};
function storyRewardModal(i,city){const c=STORY_CITY[city];modal(`<h2>Подготовка · ${esc(city)}</h2><p class="mythos-prose">${esc(c.flavor)}</p><p>После контакта выберите одну награду для этого сыщика.</p><div class="city-reward-options">${c.rewards.map((r,n)=>`<button class="${n?'ghost':'primary'}" onclick="applyStoryReward(${i},'${esc(city)}',${n})">${esc(r)}</button>`).join('')}</div>`)}

const saveContactResultV18=window.saveContactResult;
window.saveContactResult=i=>{const x=state.investigators[i],type=document.querySelector('#contact-type')?.value||'',city=document.querySelector('#contact-city')?.value||'',clues=Math.max(0,+document.querySelector('#contact-clues')?.value||0),closed=document.querySelector('#contact-gate-closed')?.checked,beforeCities=new Set(state.campaign.cities);saveContactResultV18(i);ensureStory();const st=x.storyStats;st.clues+=clues;if(type==='Поисковый контакт улики')st.clueContacts++;if(city&&!st.cities.includes(city))st.cities.push(city);if(closed)st.gates++;render();const rewardKey=`${x.name}:${city}`;if(city&&!state.storyCampaign.cityRewards[rewardKey])storyRewardModal(i,city)};

const resolveCombatV18=window.resolveCombat;
window.resolveCombat=()=>{const f=window._fight,x=f&&state.investigators[f.i],target=f&&!f.ambush&&Number.isInteger(f.stateIndex)?state.monsters[f.stateIndex]:null,beforeHp=x?.hp||0,beforeSan=x?.san||0,beforeMonster=target?.hp||0,successes=(+document.querySelector('#fight-strength-success')?.value||0)+(+document.querySelector('#fight-will-success')?.value||0);resolveCombatV18();if(!x)return;ensureStory();const st=x.storyStats,damage=target?Math.max(0,beforeMonster-target.hp):0;st.damage+=damage;st.successes+=successes;st.hpLost+=Math.max(0,beforeHp-x.hp);st.sanLost+=Math.max(0,beforeSan-x.san);if(target?.storyBossChapter)st.bossDamage+=damage;if(target&&beforeMonster>0&&target.hp===0){st.kills++;if(target.storyBossChapter)st.bossKills++}render()};

const investigatorAbilitiesV18=investigatorAbilities;
investigatorAbilities=function(x){const html=investigatorAbilitiesV18(x),s=x.storyStats||storyStats();return `${html}<section class="story-personal-stats"><h4>Летопись сыщика</h4><div class="story-stat-grid"><span><b>${s.clues}</b><small>улик получено</small></span><span><b>${(s.cities||[]).length}</b><small>городов исследовано</small></span><span><b>${s.gates}</b><small>врат закрыто</small></span><span><b>${s.damage}</b><small>урона монстрам</small></span><span><b>${s.kills}</b><small>монстров побеждено</small></span><span><b>${s.bossDamage}</b><small>урона боссам</small></span></div></section>`};

function storyFate(x,victory){const s=x.storyStats||storyStats(),conditions=(x.conditions||[]).map(c=>conditionCatalog[c.type]?.name||'').join(' '),dead=x.hp<=0||x.san<=0,dark=/Тёмная сделка|Проклятие/i.test(conditions),broken=x.san<=2||/Амнезия|Паранойя|Галлюцинации/i.test(conditions),scarred=x.hp<=2||/Травма/i.test(conditions);if(dead)return'dead';if(dark)return'dark';if(broken)return'broken';if(scarred)return'scarred';return victory?'victory':'broken'}
function storyAchievement(x){const s=x.storyStats||storyStats(),pairs=[['bossDamage','нанёс решающие раны главным чудовищам'],['kills','чаще других завершал схватки'],['clues','собрал больше всего свидетельств'],['cities','прошёл длиннейший путь между городами'],['gates','закрывал разломы между мирами'],['upgrades','изменился и стал сильнее за время расследования']];pairs[3]=['cities',(s.cities||[]).length?'исследовал '+s.cities.join(', '):'не позволил дороге отвлечь себя от главной цели'];const best=pairs.map(([k,t])=>[k==='cities'?(s.cities||[]).length:(s[k]||0),t]).sort((a,b)=>b[0]-a[0])[0];return best[0]?`Во время расследования ${x.name} ${best[1]}.`:`История ${x.name} сохранилась не в отчётах, а в памяти товарищей.`}
function storyBuildEpilogue(victory){const sc=state.storyCampaign,world=victory?'Р’льех снова уходит под воду':'Р’льех остаётся над водой';const worldText=victory?'Море смыкается над последними башнями. Открытые врата гаснут одно за другим, но рассвет застаёт сыщиков уже другими людьми. Мир не узнает, насколько близко подошёл к концу.':'Рассвет не наступает. Там, где прежде были города, поднимаются мокрые стены Р’льеха, а голоса выживших растворяются в общем сне человечества.';const cast=state.investigators.map(x=>{const p=STORY_HEROES[x.name]||{calling:`${x.name} дошёл до конца расследования.`,victory:'Память об этой ночи навсегда изменила дальнейшую жизнь.',scarred:'Полученные раны остались напоминанием о цене борьбы.',broken:'Пережитое оказалось тяжелее любой человеческой памяти.',dark:'Часть тьмы ушла вместе с выжившим.',dead:'Последняя жертва позволила остальным продолжить путь.'},f=storyFate(x,victory),s=x.storyStats||storyStats();return `<article class="epilogue-person"><h4>${esc(x.name)}</h4><p>${esc(p.calling)} ${esc(p[f])}</p><p>${esc(storyAchievement(x))}</p><p class="epilogue-stats">Улики ${s.clues} · города ${(s.cities||[]).length} · врата ${s.gates} · урон ${s.damage} · победы ${s.kills} · урон боссам ${s.bossDamage}</p></article>`}).join('');return `<div class="story-finale"><span>${victory?'ПОБЕДА, ЗА КОТОРУЮ ЗАПЛАЧЕНО':'МИР НЕ УДАЛО СПАСТИ'}</span><h3>${world}</h3><p>${worldText}</p></div><div class="epilogue-cast">${cast}</div><button class="ghost wide" onclick="copyStoryEpilogue()">Скопировать эпилог</button>`}
window.finishStoryCampaign=victory=>{ensureStory();state.storyCampaign.finished=true;state.storyCampaign.result=victory?'victory':'defeat';state.storyCampaign.epilogue=storyBuildEpilogue(victory);state.campaign.won=victory;logEvent(victory?'Ктулху повержен. Начинается эпилог.':'Р’льех поднялся. Начинается эпилог поражения.');render()};
window.copyStoryEpilogue=async()=>{const text=document.querySelector('#campaign-progress')?.innerText||'';try{await navigator.clipboard.writeText(text);alert('Эпилог скопирован.')}catch{alert('Не удалось скопировать автоматически. Выделите текст вручную.')}};

const actionV18=action;
action=function(a){if(a==='campaign-help'){modal('<h2>Сюжетная кампания Streamlined</h2><p>В начале партии приложение выбирает шесть из девяти именных городов. Каждая глава начинается литературной сценой, продолжается расследованием и заканчивается боссом.</p><p>Первый контакт каждого сыщика в именному городе даёт одну награду подготовки. Урон боссу сохраняется между боями.</p><p>После финала приложение создаёт персональный эпилог по состоянию и достижениям каждого сыщика.</p><p class="note"><b>Хоумрул:</b> главы, награды и постоянное здоровье боссов относятся к Streamlined. Проверки, физические контакты и базовый бой сохраняют официальное ядро.</p>');return}return actionV18(a)};

const renderV18=render;
render=function(){ensureStory();renderV18();renderCampaign()};
rules.push({type:'home',title:'Сюжетные главы и боссы',text:'Шесть случайных именных городов образуют маршрут трёх глав. После чек-листа появляется босс с сохраняющимся здоровьем; подготовка в городах даёт ограниченные награды.'});
renderRules();render();
