/* Streamlined v0.3 — short campaign mysteries with game-wide progress. */
const CAMPAIGN_CITIES=['Сан-Франциско','Буэнос-Айрес','Стамбул','Шанхай','Сидней'];
const CAMPAIGN_CHAPTERS=[
 {number:1,title:'Сны о затонувшем городе',story:'Незнакомые друг другу люди видят во сне чёрные башни под зелёным небом. Свидетельства ведут через два континента.',requirements:[['clues',2,'Провести 2 поисковых контакта'],['city:Сан-Франциско',1,'Исследовать Сан-Франциско'],['city:Буэнос-Айрес',1,'Исследовать Буэнос-Айрес'],['monsters',1,'Победить 1 монстра']]},
 {number:2,title:'Культ среди людей',story:'Следы складываются в сеть тайных обществ. Курьеры везут древние таблички через Стамбул и Шанхай, пока разломы множатся.',requirements:[['clues',4,'Всего провести 4 поисковых контакта'],['city:Стамбул',1,'Исследовать Стамбул'],['city:Шанхай',1,'Исследовать Шанхай'],['gates',1,'Всего закрыть 1 врата'],['monsters',3,'Всего победить 3 монстров']]},
 {number:3,title:'Звёзды заняли свои места',story:'Р’льех поднимается со дна. Последняя цепочка свидетельств ведёт в Сидней, а открытые разломы питают пробуждение Ктулху.',requirements:[['clues',5,'Всего провести 5 поисковых контактов'],['city:Сидней',1,'Исследовать Сидней'],['gates',3,'Всего закрыть 3 врат'],['monsters',6,'Всего победить 6 монстров'],['ritual',1,'Потратить 3 улики на финальный ритуал']]}
];
function campaignDefault(){return{clueContacts:0,cities:[],gatesClosed:0,monstersDefeated:0,ritual:false,chapter:1,won:false}}
function ensureCampaign(){state.campaign={...campaignDefault(),...(state.campaign||{})};state.campaign.cities=Array.isArray(state.campaign.cities)?state.campaign.cities:[];(state.monsters||[]).forEach(m=>{if(m.campaignCounted==null)m.campaignCounted=false})}
ensureCampaign();
function campaignValue(key){if(key==='clues')return state.campaign.clueContacts;if(key==='gates')return state.campaign.gatesClosed;if(key==='monsters')return state.campaign.monstersDefeated;if(key==='ritual')return state.campaign.ritual?1:0;if(key.startsWith('city:'))return state.campaign.cities.includes(key.slice(5))?1:0;return 0}
function chapterComplete(ch){return ch.requirements.every(([key,target])=>campaignValue(key)>=target)}
function updateCampaign(){let next=1;for(const ch of CAMPAIGN_CHAPTERS){if(chapterComplete(ch)){next=ch.number+1}else break}const before=state.campaign.chapter;state.campaign.chapter=Math.min(3,next);if(next>before&&next<=3)logEvent(`Глава ${before} завершена. Начинается глава ${next}: «${CAMPAIGN_CHAPTERS[next-1].title}».`);if(next===4&&!state.campaign.won){state.campaign.won=true;logEvent('Финальный ритуал завершён. Третья тайна разгадана — сыщики побеждают Ктулху!')}renderCampaign()}
function progressLine(key,target,label){const value=campaignValue(key),done=value>=target,shown=key.startsWith('city:')?(done?1:0):value;return `<li class="${done?'done':''}"><span class="mission-check">${done?'✓':'○'}</span><div><b>${esc(label)}</b><small>${key.startsWith('city:')?(done?'Контакт записан':'Ещё не исследовано'):`${Math.min(shown,target)} / ${target}`}</small></div></li>`}
function renderCampaign(){const root=document.querySelector('#campaign-progress');if(!root)return;const ch=CAMPAIGN_CHAPTERS[state.campaign.chapter-1],completed=CAMPAIGN_CHAPTERS.filter(chapterComplete).length;if(state.campaign.won){root.innerHTML=`<div class="campaign-victory"><span>ТРИ ТАЙНЫ РАЗГАДАНЫ</span><h3>Р’льех снова уходит под воду</h3><p>Собранные свидетельства позволили завершить ритуал до пробуждения Ктулху. Сыщики победили.</p></div>${campaignTotals()}`;return}root.innerHTML=`<div class="chapter-tabs">${CAMPAIGN_CHAPTERS.map(c=>`<button type="button" class="${c.number===state.campaign.chapter?'active':''} ${chapterComplete(c)?'complete':''}" onclick="previewChapter(${c.number})"><span>Тайна ${c.number}</span><b>${esc(c.title)}</b></button>`).join('')}</div><div class="chapter-current"><div class="chapter-story"><span>АКТИВНАЯ ГЛАВА · ${completed}/3 РАЗГАДАНО</span><h3>${esc(ch.title)}</h3><p>${esc(ch.story)}</p><p class="carry-note">Все счётчики общие для партии. Лишний прогресс переносится в следующие главы.</p></div><ol class="mission-list">${ch.requirements.map(r=>progressLine(...r)).join('')}</ol></div>${campaignTotals()}${state.campaign.chapter===3&&!state.campaign.ritual?`<button class="primary ritual-button" type="button" onclick="ritualModal()" ${totalInvestigatorClues()<3?'disabled':''}>Провести финальный ритуал · потратить 3 улики</button>`:''}`}
function campaignTotals(){return `<div class="campaign-totals"><span><b>${state.campaign.clueContacts}</b><small>поисковых контактов</small></span><span><b>${state.campaign.cities.length}</b><small>городов исследовано</small></span><span><b>${state.campaign.gatesClosed}</b><small>врат закрыто</small></span><span><b>${state.campaign.monstersDefeated}</b><small>монстров побеждено</small></span></div>`}
window.previewChapter=n=>{const ch=CAMPAIGN_CHAPTERS[n-1];modal(`<h2>Тайна ${n} · ${esc(ch.title)}</h2><p class="mythos-prose">${esc(ch.story)}</p><ol class="mission-list preview">${ch.requirements.map(r=>progressLine(...r)).join('')}</ol><p class="note">Это хоумрул Streamlined v0.3. Физическая карта тайны в этой партии не используется.</p>`)};
function totalInvestigatorClues(){return state.investigators.reduce((n,x)=>n+(+x.clues||0),0)}
window.ritualModal=()=>{if(totalInvestigatorClues()<3)return alert('У группы пока меньше 3 улик.');modal(`<h2>Финальный ритуал</h2><p>Распределите три улики между сыщиками. Всего нужно потратить ровно 3.</p><div class="form-stack">${state.investigators.filter(x=>x.clues>0).map((x,i)=>`<label>${esc(x.name)} · доступно ${x.clues}<input class="ritual-clue" data-name="${esc(x.name)}" type="number" min="0" max="${x.clues}" value="0"></label>`).join('')}<button class="primary" type="button" onclick="completeRitual()">Завершить ритуал</button></div>`)};
window.completeRitual=()=>{const inputs=[...document.querySelectorAll('.ritual-clue')],sum=inputs.reduce((n,e)=>n+(+e.value||0),0);if(sum!==3)return alert('Для ритуала нужно потратить ровно 3 улики.');for(const e of inputs){const x=state.investigators.find(z=>z.name===e.dataset.name),n=+e.value||0;if(!x||n>x.clues)return alert('Проверьте количество улик.');x.clues-=n}state.campaign.ritual=true;logEvent('Сыщики потратили 3 улики и завершили финальный ритуал.');document.querySelector('#modal').close();updateCampaign();render()};

function cityOptions(selected=''){return `<option value="">Не относится к требуемому городу</option>${CAMPAIGN_CITIES.map(c=>`<option ${c===selected?'selected':''}>${c}</option>`).join('')}`}
window.contactResultModal=i=>{const x=state.investigators[i];if(!x||!canEdit(x))return;const monsters=state.monsters.filter(m=>!x.location||m.location===x.location);modal(`<h2>Результат контакта · ${esc(x.name)}</h2>${monsters.length?`<div class="combat-warning"><b>В этой локации записаны монстры.</b> Сначала проведите бой со всеми. Если хоть один остался, другой контакт не проводится.</div>`:''}<div class="form-stack"><label>Какой контакт проведён<select id="contact-type"><option>Контакт локации</option><option>Поисковый контакт улики</option><option>Контакт в Ином мире</option><option>Экспедиционный контакт</option><option>Особый контакт тайны или слуха</option><option>Только боевой контакт</option></select></label><label>Требуемый город расследования<select id="contact-city">${cityOptions()}</select></label><p class="field-help">Город засчитывается за прохождение его физического контакта — независимо от успеха или провала.</p><label>Получено улик в инвентарь<input id="contact-clues" type="number" min="0" value="0"></label><label>Изменение здоровья<input id="contact-hp" type="number" value="0"></label><label>Изменение рассудка<input id="contact-san" type="number" value="0"></label><label class="inline-check"><input id="contact-gate-closed" type="checkbox"> В ходе контакта закрыты врата</label><label>Знак закрытых врат<select id="contact-gate-sign"><option value="0">● — круг</option><option value="1">☄ — комета</option><option value="2">◐ — полумесяц</option><option value="3">✦ — созвездие</option></select></label><label>Где выложен жетон Древних<input id="contact-elder" placeholder="Оставьте пустым, если не выкладывали"></label><label>Что ещё произошло<textarea id="contact-note" placeholder="Получена вещь, состояние, сюжетный результат…"></textarea></label><button class="primary" type="button" onclick="saveContactResult(${i})">Записать результат</button></div>`)};
window.saveContactResult=i=>{const x=state.investigators[i],type=document.querySelector('#contact-type').value,city=document.querySelector('#contact-city').value,clues=Math.max(0,+document.querySelector('#contact-clues').value),hp=+document.querySelector('#contact-hp').value||0,san=+document.querySelector('#contact-san').value||0,closed=document.querySelector('#contact-gate-closed').checked,sign=+document.querySelector('#contact-gate-sign').value,elder=document.querySelector('#contact-elder').value.trim(),note=document.querySelector('#contact-note').value.trim();x.clues+=clues;x.hp=Math.max(0,Math.min(x.hpMax,x.hp+hp));x.san=Math.max(0,Math.min(x.sanMax,x.san+san));x.contactDone=true;if(type==='Поисковый контакт улики')state.campaign.clueContacts++;if(city&&!state.campaign.cities.includes(city))state.campaign.cities.push(city);if(closed){state.campaign.gatesClosed++;state.gates[sign]=Math.max(0,(state.gates[sign]||0)-1);const gateIndex=state.openGates.findIndex(g=>g.sign===sign);if(gateIndex>=0)state.openGates.splice(gateIndex,1)}if(elder)state.elderTokens.push({location:elder,round:state.round,source:x.name});logEvent(`${x.name}: ${type}${city?` в городе ${city}`:''}. ${clues?`Получено улик: ${clues}. `:''}${closed?'Врата закрыты. ':''}${hp?`HP ${hp>0?'+':''}${hp}. `:''}${san?`SAN ${san>0?'+':''}${san}. `:''}${elder?`Жетон Древних: ${elder}. `:''}${note}`.trim());document.querySelector('#modal').close();updateCampaign();render()};

const resolveCombatV13=window.resolveCombat;
window.resolveCombat=()=>{const f=window._fight,target=!f?.ambush&&Number.isInteger(f?.stateIndex)?state.monsters[f.stateIndex]:null,wasDefeated=target?.hp===0;resolveCombatV13();if(target&&!wasDefeated&&target.hp===0&&!target.campaignCounted){target.campaignCounted=true;state.campaign.monstersDefeated++;logEvent(`Победа над ${target.name} продвигает общее расследование: ${state.campaign.monstersDefeated}/6.`);updateCampaign();render()}};
document.addEventListener('click',e=>{const b=e.target.closest('[data-monster-hp]');if(!b)return;const m=state.monsters[+b.dataset.monsterHp];if(m?.hp===0&&!m.campaignCounted){m.campaignCounted=true;state.campaign.monstersDefeated++;logEvent(`Победа над ${m.name} продвигает расследование: ${state.campaign.monstersDefeated}/6.`);updateCampaign();render()}},{capture:false});

const actionV13=action;
action=function(a){if(a==='campaign-help'){modal('<h2>Новое расследование Streamlined v0.3</h2><p>Три короткие главы заменяют официальные карты тайн Ктулху. Счётчики общие для всей партии: пять поисковых контактов, пять заданных городов, три закрытых врата и шесть монстров.</p><p>Один контакт может выполнить сразу несколько задач. Например, поисковый контакт в Сан-Франциско засчитает и улику, и город. Прогресс сверх требования переносится дальше.</p><p class="note"><b>Официальное правило:</b> сами контакты, бои и закрытие врат по-прежнему разыгрываются физическими компонентами. Приложение только ведёт сюжет и считает результат.</p>');return}return actionV13(a)};

rules.push({type:'home',title:'Три главы расследования Ктулху',text:'Официальные карты тайн заменены единым расследованием на всю партию: 5 поисковых контактов, контакты в Сан-Франциско, Буэнос-Айресе, Стамбуле, Шанхае и Сиднее, 3 закрытых врат, 6 побеждённых монстров и финальный ритуал за 3 улики. Прогресс переносится между главами.'});
const renderV13=render;
render=function(){ensureCampaign();renderV13();renderCampaign();const completed=CAMPAIGN_CHAPTERS.filter(chapterComplete).length,field=document.querySelector('#mystery-total');if(field){field.value=completed;field.disabled=true;field.closest('label').childNodes[0].textContent='Глав завершено'}};
renderRules();
updateCampaign();render();
